In [1]:
import numpy as np

In [3]:
import numpy as np

# Data structure:
# [student_id, Math, Science, English, Computer]

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])


print(a[:,:].astype(float))#Q1. Print the entire array.
print("\n",a[:,0])#Q2. Print only the Student IDs.
print("\n",a[:,4])#Q3. Print Computer scores of all students.
print("\n",a[3,1:])#Q4. Print all subject scores of Student 104.
print("\n",a.shape,a.ndim,a.shape,a.dtype)

[[101.  78.  85.  90.  88.]
 [102.  92.  80.  84.  95.]
 [103.  65.  70.  72.  68.]
 [104.  88.  91.  89.  93.]
 [105.  74.  76.  80.  79.]
 [106.  96.  94.  98.  97.]]

 [101 102 103 104 105 106]

 [88 95 68 93 79 97]

 [88 91 89 93]

 (6, 5) 2 (6, 5) int64


In [4]:
# [student_id, Math, Science, English, Computer]

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

print(np.sum(a[:,1:],axis=1))#Q9. Find the total marks of each student.
print(np.sum(a[:,1:],axis=0))#Q10. Find total marks obtained in each subject.

print(np.mean(a[:,1:],axis=1))#Average marks of each student
print(np.mean(a[:,1:],axis=0))#Average marks of each subject

print(np.max(a[:,1:]))#Highest mark
print(np.min(a[:,1:]))#lowest mark

cs=(np.argmax(a[:,4]))#Student ID with highest Computer score
si=a[cs,0]
print(si)

ls=np.argmin(a[:,1])#Student ID with lowest Math score
si=a[ls,0]
print(si)

[341 351 275 361 309 385]
[493 496 513 520]
[85.25 87.75 68.75 90.25 77.25 96.25]
[82.16666667 82.66666667 85.5        86.66666667]
98
65
106
103


In [5]:
# [student_id, Math, Science, English, Computer]

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

c=a[:,4]>90 #Students scoring above 90 in Computer
si=a[c,0]
print(si)


[102 104 106]


In [6]:
# [student_id, Math, Science, English, Computer]

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])
d=a[:,3]>85 #Rows where English > 85
s2=a[d]
print(s2)


[[101  78  85  90  88]
 [104  88  91  89  93]
 [106  96  94  98  97]]


In [7]:
# [student_id, Math, Science, English, Computer]

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])                        #Count students scoring above 80 in Science
c=0
a80=np.sum(a[:,2]>80)
print(a80)



3


In [8]:
# [student_id, Math, Science, English, Computer]

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])


t=np.sum(a[:,1:],axis=1)>350,0#Add 5 grace marks
print(a[t])

newdata=a.copy()
newdata[:,1:]=newdata[:,1:]+5
print(newdata)
# g=a[:,1:]+5
# print(g)

[102 104 106]
[[101  83  90  95  93]
 [102  97  85  89 100]
 [103  70  75  77  73]
 [104  93  96  94  98]
 [105  79  81  85  84]
 [106 101  99 103 102]]


In [9]:
# [student_id, Math, Science, English, Computer]
#Math +2
# Science +3
# English +4
# Computer +5

a = np.array([
    [101, 78, 85, 90, 88],

    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

newdata=a.copy()
newdata[:,1]=newdata[:,1]+2
newdata[:,2]=newdata[:,2]+3
newdata[:,3]=newdata[:,3]+4
newdata[:,4]=newdata[:,4]+5

print(newdata)


[[101  80  88  94  93]
 [102  94  83  88 100]
 [103  67  73  76  73]
 [104  90  94  93  98]
 [105  76  79  84  84]
 [106  98  97 102 102]]


In [10]:
# [student_id, Math, Science, English, Computer]#Increase all marks by 10%

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

f=a[:,1:]*1.10
print(f)

[[ 85.8  93.5  99.   96.8]
 [101.2  88.   92.4 104.5]
 [ 71.5  77.   79.2  74.8]
 [ 96.8 100.1  97.9 102.3]
 [ 81.4  83.6  88.   86.9]
 [105.6 103.4 107.8 106.7]]


In [11]:
# [student_id, Math, Science, English, Computer]

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])
newdata=a.copy().astype(float)
newdata[:,1]=newdata[:,1]*1.05
newdata[:,2]=newdata[:,2]*1.06
newdata[:,3]=newdata[:,3]*1.07
newdata[:,4]=newdata[:,4]*1.08
print(newdata)
print(newdata[:, 1:])
#Apply growth:

# Math +5%
# Science +6%
# English +7%
# Computer +8%

[[101.    81.9   90.1   96.3   95.04]
 [102.    96.6   84.8   89.88 102.6 ]
 [103.    68.25  74.2   77.04  73.44]
 [104.    92.4   96.46  95.23 100.44]
 [105.    77.7   80.56  85.6   85.32]
 [106.   100.8   99.64 104.86 104.76]]
[[ 81.9   90.1   96.3   95.04]
 [ 96.6   84.8   89.88 102.6 ]
 [ 68.25  74.2   77.04  73.44]
 [ 92.4   96.46  95.23 100.44]
 [ 77.7   80.56  85.6   85.32]
 [100.8   99.64 104.86 104.76]]


In [12]:
# [student_id, Math, Science, English, Computer]#Shape after extracting subject columns

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

c=a[:,1:]
print(c.shape)

(6, 4)


In [13]:
# [student_id, Math, Science, English, Computer]#Shape after extracting subject columns

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

print(a[0:3,:])#First 3 students
f=a[:,1:3]
print(f.shape)#Shape of Science and English columns

print(a[::-1])#Reverse students
print(a[:,:-5:-1])

c=(np.diff(a[:,1:],axis=1))#Subject-wise differences
print(c)
print(c.shape)

pi=((a[:,4]-a[:,3])/a[:,3])*100#Percentage increase from English to Computer
print(pi)

[[101  78  85  90  88]
 [102  92  80  84  95]
 [103  65  70  72  68]]
(6, 2)
[[106  96  94  98  97]
 [105  74  76  80  79]
 [104  88  91  89  93]
 [103  65  70  72  68]
 [102  92  80  84  95]
 [101  78  85  90  88]]
[[88 90 85 78]
 [95 84 80 92]
 [68 72 70 65]
 [93 89 91 88]
 [79 80 76 74]
 [97 98 94 96]]
[[  7   5  -2]
 [-12   4  11]
 [  5   2  -4]
 [  3  -2   4]
 [  2   4  -1]
 [ -2   4  -1]]
(6, 3)
[-2.22222222 13.0952381  -5.55555556  4.49438202 -1.25       -1.02040816]


In [14]:
# [student_id, Math, Science, English, Computer]#Shape after extracting subject columns

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

t=np.sum(a[:,1:],axis=1)#Student ID with highest total
c=np.argmax(t)
si=a[c,0]
print(si)

106


In [15]:
# [student_id, Math, Science, English, Computer]#Shape after extracting subject columns

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

sor=np.argsort((a[:,4]))#Students sorted by Computer scores
si=a[sor,0]
print(si)

t=np.sum(a[:,1:],axis=1) #Students sorted by total marks
arso=np.argsort(t)
si=a[arso,0]
print(si)
t = np.sum(a[:, 1:], axis=1)#Shape after adding total column

newcol = np.hstack((a, t.reshape(-1, 1)))

print(newcol)


[103 105 101 104 102 106]
[103 105 101 102 104 106]
[[101  78  85  90  88 341]
 [102  92  80  84  95 351]
 [103  65  70  72  68 275]
 [104  88  91  89  93 361]
 [105  74  76  80  79 309]
 [106  96  94  98  97 385]]


In [16]:
# [student_id, Math, Science, English, Computer]#Shape after extracting subject columns

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
])

print(np.where(a[:,1:]<75,75,a[:,1:]))
print(np.where(a[:,1:]>95,95,a[:,1:]))
t=(np.sum(a[:,1:],axis=1))#Top 3 students by total marks
s=np.argsort(t)[-3:]
si=a[s,0]

print(si)

[[78 85 90 88]
 [92 80 84 95]
 [75 75 75 75]
 [88 91 89 93]
 [75 76 80 79]
 [96 94 98 97]]
[[78 85 90 88]
 [92 80 84 95]
 [65 70 72 68]
 [88 91 89 93]
 [74 76 80 79]
 [95 94 95 95]]
[102 104 106]


In [2]:
import numpy as np #10/6/26
# [student_id, Math, Science, English, Computer]#Shape after extracting subject columns

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
]) 

v=np.var(a[:,1:],axis=0)#Variance of each subject
print(v)

s=np.std(a[:,1:],axis=0)#Standard deviation of each subject
print(s)


m=a[:,1]
e=a[:,4]
c=np.corrcoef(m,e)
print(c)

#Very strong positive correlation.

[116.80555556  69.22222222  67.25       104.22222222]
[10.80766189  8.31998932  8.20060973 10.20892855]
[[1.         0.96574881]
 [0.96574881 1.        ]]


In [3]:
import numpy as np
# [student_id, Math, Science, English, Computer]#Shape after extracting subject columns

a = np.array([
    [101, 78, 85, 90, 88],
    [102, 92, 80, 84, 95],
    [103, 65, 70, 72, 68],
    [104, 88, 91, 89, 93],
    [105, 74, 76, 80, 79],
    [106, 96, 94, 98, 97]
]) 

p=((a[:,1:])/100)*100  #Convert marks into percentages out of 100
print(p)

s=np.sum(a[:,1:],axis=1)  #Find each student's overall percentage.
esp=(s/400)*100
print("\n",esp)

[[78. 85. 90. 88.]
 [92. 80. 84. 95.]
 [65. 70. 72. 68.]
 [88. 91. 89. 93.]
 [74. 76. 80. 79.]
 [96. 94. 98. 97.]]

 [85.25 87.75 68.75 90.25 77.25 96.25]
