#### First One Employee Related

In [1]:
import numpy as np

# Columns:
# [Employee_ID, Age, Experience_Years, Salary,
#  Projects_Completed, Performance_Score,
#  Training_Hours, Attendance_Percentage]

a = np.array([
    [101, 25,  2, 45000,  5, 78, 20, 92],
    [102, 30,  5, 60000,  8, 85, 25, 95],
    [103, 28,  4, 55000,  7, 82, 18, 88],
    [104, 35, 10, 85000, 12, 91, 30, 97],
    [105, 40, 15, 95000, 15, 94, 35, 99],
    [106, 26,  3, 48000,  6, 76, 15, 90],
    [107, 32,  7, 70000, 10, 88, 28, 96],
    [108, 29,  5, 62000,  9, 84, 22, 91],
    [109, 45, 20,120000, 18, 97, 40,100],
    [110, 38, 12, 90000, 14, 92, 32, 98]
])


print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
print(a[0])
print(a[-1])
print(a[:,0])
print(a[:,3])
print(a[:,2:4])
print(a[0:5,:])
print(a[3:8,:])
print(a[0::2,0])
print(a[5,5])
print(a[:,-4:])
print(np.mean(a[:,3]))
print(np.max(a[:,3]))
print(np.min(a[:,3]))
print(np.sum(a[:,4]))
print(np.mean(a[:,-1]))
print(np.sum(a[:,3]))
print(np.mean(a[:,5]))
print(np.median(a[:,3]))
print(np.std(a[:,3]))
print(np.var(a[:,5]))


[[   101     25      2  45000      5     78     20     92]
 [   102     30      5  60000      8     85     25     95]
 [   103     28      4  55000      7     82     18     88]
 [   104     35     10  85000     12     91     30     97]
 [   105     40     15  95000     15     94     35     99]
 [   106     26      3  48000      6     76     15     90]
 [   107     32      7  70000     10     88     28     96]
 [   108     29      5  62000      9     84     22     91]
 [   109     45     20 120000     18     97     40    100]
 [   110     38     12  90000     14     92     32     98]]
(10, 8)
80
2
int64
[  101    25     2 45000     5    78    20    92]
[  110    38    12 90000    14    92    32    98]
[101 102 103 104 105 106 107 108 109 110]
[ 45000  60000  55000  85000  95000  48000  70000  62000 120000  90000]
[[     2  45000]
 [     5  60000]
 [     4  55000]
 [    10  85000]
 [    15  95000]
 [     3  48000]
 [     7  70000]
 [     5  62000]
 [    20 120000]
 [    12  90000]]
[[  1

In [2]:
import numpy as np

# Columns:
# [Employee_ID, Age, Experience_Years, Salary,
#  Projects_Completed, Performance_Score,
#  Training_Hours, Attendance_Percentage]

a = np.array([
    [101, 25,  2, 45000,  5, 78, 20, 92],
    [102, 30,  5, 60000,  8, 85, 25, 95],
    [103, 28,  4, 55000,  7, 82, 18, 88],
    [104, 35, 10, 85000, 12, 91, 30, 97],
    [105, 40, 15, 95000, 15, 94, 35, 99],
    [106, 26,  3, 48000,  6, 76, 15, 90],
    [107, 32,  7, 70000, 10, 88, 28, 96],
    [108, 29,  5, 62000,  9, 84, 22, 91],
    [109, 45, 20,120000, 18, 97, 40,100],
    [110, 38, 12, 90000, 14, 92, 32, 98]
])

print(a[a[:,3]>70000,0])
print(a[a[:,1]>35,0])
print(a[a[:,5]>90,0])
print(a[a[:,-1]<95,0])
print(a[a[:,2]>10,0])
print(a[(a[:,3] > 60000) & (a[:,-1] > 95), 0])#*
print(a[(a[:,5]<80) | (a[:,-1]<90),0])
print(np.argmax(a[:,3]))
print(a[np.argmax(a[:,3]),0])
print(a[np.argsort(a[:,1]),0])
print(a[np.argsort(a[:,3]),0])
print(a[np.argsort(a[:,3])[::-1], 0])
print(np.argsort(a[:,-1]))
print(np.column_stack((a, a[:,3] * 0.10)))#*
print(a[:,3]*1.05)

print(a[np.argsort(a[:,3])[::-1][0:3], 0])#*41. Top 3 highest-paid Employee IDs.
print(a[a[:,5]>np.mean(a[:,5]),0])#*42. Employees with performance above average.

# IMP-45. Create array with Employee_ID, Salary, Performance.
print(np.array((a[:,0],a[:,3],a[:,5])))
print(a[:, [0, 3, 5]])

[104 105 109 110]
[105 109 110]
[104 105 109 110]
[101 103 106 108]
[105 109 110]
[104 105 107 109 110]
[101 103 106]
8
109
[101 106 103 108 102 107 104 110 105 109]
[101 106 103 102 108 107 104 110 105 109]
[109 105 110 104 107 108 102 103 106 101]
[2 5 7 0 1 6 3 9 4 8]
[[1.01e+02 2.50e+01 2.00e+00 4.50e+04 5.00e+00 7.80e+01 2.00e+01 9.20e+01
  4.50e+03]
 [1.02e+02 3.00e+01 5.00e+00 6.00e+04 8.00e+00 8.50e+01 2.50e+01 9.50e+01
  6.00e+03]
 [1.03e+02 2.80e+01 4.00e+00 5.50e+04 7.00e+00 8.20e+01 1.80e+01 8.80e+01
  5.50e+03]
 [1.04e+02 3.50e+01 1.00e+01 8.50e+04 1.20e+01 9.10e+01 3.00e+01 9.70e+01
  8.50e+03]
 [1.05e+02 4.00e+01 1.50e+01 9.50e+04 1.50e+01 9.40e+01 3.50e+01 9.90e+01
  9.50e+03]
 [1.06e+02 2.60e+01 3.00e+00 4.80e+04 6.00e+00 7.60e+01 1.50e+01 9.00e+01
  4.80e+03]
 [1.07e+02 3.20e+01 7.00e+00 7.00e+04 1.00e+01 8.80e+01 2.80e+01 9.60e+01
  7.00e+03]
 [1.08e+02 2.90e+01 5.00e+00 6.20e+04 9.00e+00 8.40e+01 2.20e+01 9.10e+01
  6.20e+03]
 [1.09e+02 4.50e+01 2.00e+01 1.20e+05 1.

### Students Related

In [3]:
import numpy as np

# Columns:
# [Student_ID, Age, Study_Hours,
#  Math, Science, English,
#  Attendance, Projects]

a = np.array([
    [201,18,3,78,82,75,92,2],
    [202,19,4,85,88,90,95,3],
    [203,20,2,65,70,68,85,1],
    [204,18,5,92,95,91,98,4],
    [205,21,6,88,84,86,96,5],
    [206,19,1,55,60,58,80,0],
    [207,20,4,80,78,82,90,2],
    [208,22,7,95,98,97,99,6],
    [209,18,3,72,75,70,88,1],
    [210,21,5,90,92,89,97,4],
    [211,20,2,68,65,72,84,1],
    [212,19,6,87,89,85,94,5]
])

print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

print(a[0])
print(a[-1])
print(a[:,0])
print(a[:,3])
print(a[:,4:6])
print(a[:6,:])
print(a[-1:-6:-1,:])
print(a[0::2,:])
print(a[3:9,:])
print(a[:,0:3])
print(a[:,-1:-4:-1])

(12, 8)
96
2
int64
[201  18   3  78  82  75  92   2]
[212  19   6  87  89  85  94   5]
[201 202 203 204 205 206 207 208 209 210 211 212]
[78 85 65 92 88 55 80 95 72 90 68 87]
[[82 75]
 [88 90]
 [70 68]
 [95 91]
 [84 86]
 [60 58]
 [78 82]
 [98 97]
 [75 70]
 [92 89]
 [65 72]
 [89 85]]
[[201  18   3  78  82  75  92   2]
 [202  19   4  85  88  90  95   3]
 [203  20   2  65  70  68  85   1]
 [204  18   5  92  95  91  98   4]
 [205  21   6  88  84  86  96   5]
 [206  19   1  55  60  58  80   0]]
[[212  19   6  87  89  85  94   5]
 [211  20   2  68  65  72  84   1]
 [210  21   5  90  92  89  97   4]
 [209  18   3  72  75  70  88   1]
 [208  22   7  95  98  97  99   6]]
[[201  18   3  78  82  75  92   2]
 [203  20   2  65  70  68  85   1]
 [205  21   6  88  84  86  96   5]
 [207  20   4  80  78  82  90   2]
 [209  18   3  72  75  70  88   1]
 [211  20   2  68  65  72  84   1]]
[[204  18   5  92  95  91  98   4]
 [205  21   6  88  84  86  96   5]
 [206  19   1  55  60  58  80   0]
 [207  20   4

In [4]:
import numpy as np

# Columns:
# [Student_ID, Age, Study_Hours,
#  Math, Science, English,
#  Attendance, Projects]

a = np.array([
    [201,18,3,78,82,75,92,2],
    [202,19,4,85,88,90,95,3],
    [203,20,2,65,70,68,85,1],
    [204,18,5,92,95,91,98,4],
    [205,21,6,88,84,86,96,5],
    [206,19,1,55,60,58,80,0],
    [207,20,4,80,78,82,90,2],
    [208,22,7,95,98,97,99,6],
    [209,18,3,72,75,70,88,1],
    [210,21,5,90,92,89,97,4],
    [211,20,2,68,65,72,84,1],
    [212,19,6,87,89,85,94,5]
])


print(np.mean(a[:,3]))
print(np.mean(a[:,4]))
print(np.mean(a[:,5]))
print(np.max(a[:,3]))
print(np.median(a[:,5]))
print(np.mean(a[:,3]))
print(np.sum(a[:,-1]))
print(np.mean(a[:,6]))
print(np.std(a[:,3]))
print(np.var(a[:,4]))
print(a[a[:,3]>85,0])
print(a[a[:,4]>90,0])
print(a[a[:,6]>95,0])
print(a[a[:,2]>5,0])
print(a[a[:,-1]>=4,0])
print(a[(a[:,3]>80) & (a[:,-2]>95),0])
print(a[(a[:,4]>85) & (a[:,-1]>3),0])
print(a[a[:,5]<70,0])
print(a[a[:,-2]<90,0])
print(a[a[:,1]>20,0])
print(np.argmax(a[:,3]))
print(a[np.argmax(a[:,3]),0])
print(np.argmin(a[:,-2]))
print(a[np.argmin(a[:,5]),0])
print(a[np.argmax(a[:,-1]),0])









79.58333333333333
81.33333333333333
80.25
95
83.5
79.58333333333333
34
91.5
11.78599687010913
132.55555555555557
[204 205 208 210 212]
[204 208 210]
[204 205 208 210]
[205 208 212]
[204 205 208 210 212]
[204 205 208 210]
[204 208 210 212]
[203 206]
[203 206 209 211]
[205 208 210]
7
208
5
206
208


In [5]:
import numpy as np

# Columns:
# [Student_ID, Age, Study_Hours,
#  Math, Science, English,
#  Attendance, Projects]

a = np.array([
    [201,18,3,78,82,75,92,2],
    [202,19,4,85,88,90,95,3],
    [203,20,2,65,70,68,85,1],
    [204,18,5,92,95,91,98,4],
    [205,21,6,88,84,86,96,5],
    [206,19,1,55,60,58,80,0],
    [207,20,4,80,78,82,90,2],
    [208,22,7,95,98,97,99,6],
    [209,18,3,72,75,70,88,1],
    [210,21,5,90,92,89,97,4],
    [211,20,2,68,65,72,84,1],
    [212,19,6,87,89,85,94,5]
])

print(a[np.argsort(a[:,3]),0])
print(a[np.argsort(a[:,4])[::-1],0])
print(a[np.argsort(a[:,-2]),0])
print(a[np.argsort(a[:,3])[::-1][0:5],0])
print(a[np.argsort(a[:,-2])[::-1][0:3],0])
b=np.column_stack((a,np.sum(a[:,3:6],axis=1)))
print(b.shape)
print(np.column_stack((a,np.sum(a[:,3:6],axis=1))))
print(np.column_stack((a,np.mean(a[:,3:6],axis=1))))
print(np.column_stack((np.mean(a[:,3:6],axis=1))))
print(a[:,3:6]+5)

# print(a[:,[0,3,4,5,np.sum(a[:,3:6])]])
# result = np.column_stack((a[:,[0,3,4,5]], total))

# print(result)

print(np.column_stack((a[:, [0, 3, 4, 5]],np.sum(a[:,3:6], axis=1))))


[206 203 211 209 201 207 202 212 205 210 204 208]
[208 204 210 212 202 205 201 207 209 203 211 206]
[206 211 203 209 207 201 212 202 205 210 204 208]
[208 204 210 205 212]
[208 204 210]
(12, 9)
[[201  18   3  78  82  75  92   2 235]
 [202  19   4  85  88  90  95   3 263]
 [203  20   2  65  70  68  85   1 203]
 [204  18   5  92  95  91  98   4 278]
 [205  21   6  88  84  86  96   5 258]
 [206  19   1  55  60  58  80   0 173]
 [207  20   4  80  78  82  90   2 240]
 [208  22   7  95  98  97  99   6 290]
 [209  18   3  72  75  70  88   1 217]
 [210  21   5  90  92  89  97   4 271]
 [211  20   2  68  65  72  84   1 205]
 [212  19   6  87  89  85  94   5 261]]
[[201.          18.           3.          78.          82.
   75.          92.           2.          78.33333333]
 [202.          19.           4.          85.          88.
   90.          95.           3.          87.66666667]
 [203.          20.           2.          65.          70.
   68.          85.           1.          67.66666