In [1]:
import numpy as np

# Columns:
# [Order ID, Customer Age, Items Purchased,
#  Order Value ($), Discount (%),
#  Delivery Days, Customer Rating]

a = np.array([
    [1001, 25, 2, 1200, 10, 3, 5],   # Order 1001
    [1002, 32, 1,  800,  5, 5, 4],   # Order 1002
    [1003, 45, 4, 2500, 15, 2, 5],   # Order 1003
    [1004, 29, 3, 1800,  0, 4, 3],   # Order 1004
    [1005, 38, 5, 3200, 20, 6, 4],   # Order 1005
    [1006, 23, 2,  950,  5, 3, 2],   # Order 1006
    [1007, 41, 6, 4100, 25, 7, 5],   # Order 1007
    [1008, 35, 1,  700,  0, 2, 4],   # Order 1008
    [1009, 27, 3, 1600, 10, 5, 3],   # Order 1009
    [1010, 50, 7, 5000, 30, 8, 5]    # Order 1010
])

In [2]:
print("\n", a.shape, "\n")   # What is the shape of the dataset?

print("\n", a.ndim, "\n")    # How many dimensions?

print("\n", a.size, "\n")    # Total number of elements

print("\n", a.dtype, "\n")   # Datatype of array

print("\n", a[0], "\n")      # First order details

print("\n", a[-1], "\n")     # Last order details

print("\n", a[:,1], "\n")    # Customer ages

print("\n", np.mean(a[:,1]), "\n")   # Average customer age

print("\n", np.max(a[:,3]), "\n")    # Highest order value

print("\n", np.min(a[:,3]), "\n")    # Lowest order value


 (10, 7) 


 2 


 70 


 int64 


 [1001   25    2 1200   10    3    5] 


 [1010   50    7 5000   30    8    5] 


 [25 32 45 29 38 23 41 35 27 50] 


 34.5 


 5000 


 700 



In [3]:
print("\n", np.sum(a[:,3]), "\n")    # Total revenue generated

print("\n", np.mean(a[:,6]), "\n")   # Average customer rating

print("\n", np.std(a[:,3]), "\n")    # standard deviation in order values

print("\n", np.var(a[:,5]), "\n")    # Variance of delivery time

print("\n", np.median(a[:,3]), "\n")   # Median order value

print("\n", np.sort(a[:,3]), "\n")   # Order values sorted

print("\n", np.argsort(a[:,3]), "\n")   # Positions after sorting

print("\n", a[a[:,3] > 2000], "\n")   # Orders above $2000

print("\n", a[a[:,6] == 5][:,1], "\n")   # Ages of customers giving 5-star ratings

print("\n", np.count_nonzero(a[:,4]), "\n")   # Number of discounted orders



 21850 


 4.0 


 1408.1992046582045 


 3.85 


 1700.0 


 [ 700  800  950 1200 1600 1800 2500 3200 4100 5000] 


 [7 1 5 0 8 3 2 4 6 9] 


 [[1003   45    4 2500   15    2    5]
 [1005   38    5 3200   20    6    4]
 [1007   41    6 4100   25    7    5]
 [1010   50    7 5000   30    8    5]] 


 [25 45 41 50] 


 8 



In [4]:
print("\n", np.unique(a[:,6]), "\n")   # Unique ratings received

print(
    "\n",
    np.vstack((a, np.mean(a, axis=0))),
    "\n"
)   # Dataset with average row


print("\n", a.flatten(), "\n")   # Convert dataset into 1D



print("\n", a.T, "\n")   # Rows become columns


print(
    "\n",
    a[np.argmax(a[:,3])],
    "\n"
)   # Complete details of highest-value order



print(
    "\n",
    a[np.argmin(a[:,6])],
    "\n"
)   # Complete details of lowest-rated order




print(
    "\n",
    a[:,3] * 1.10,
    "\n"
)   # Order values after 10% increase


print("\n", np.cumsum(a[:,3]), "\n")# Find cumulative sales.


print(
    "\n",
    a[a[:,1] > np.mean(a[:,1])],
    "\n"
)# Find customers whose age is above average.


 [2 3 4 5] 


 [[1.0010e+03 2.5000e+01 2.0000e+00 1.2000e+03 1.0000e+01 3.0000e+00
  5.0000e+00]
 [1.0020e+03 3.2000e+01 1.0000e+00 8.0000e+02 5.0000e+00 5.0000e+00
  4.0000e+00]
 [1.0030e+03 4.5000e+01 4.0000e+00 2.5000e+03 1.5000e+01 2.0000e+00
  5.0000e+00]
 [1.0040e+03 2.9000e+01 3.0000e+00 1.8000e+03 0.0000e+00 4.0000e+00
  3.0000e+00]
 [1.0050e+03 3.8000e+01 5.0000e+00 3.2000e+03 2.0000e+01 6.0000e+00
  4.0000e+00]
 [1.0060e+03 2.3000e+01 2.0000e+00 9.5000e+02 5.0000e+00 3.0000e+00
  2.0000e+00]
 [1.0070e+03 4.1000e+01 6.0000e+00 4.1000e+03 2.5000e+01 7.0000e+00
  5.0000e+00]
 [1.0080e+03 3.5000e+01 1.0000e+00 7.0000e+02 0.0000e+00 2.0000e+00
  4.0000e+00]
 [1.0090e+03 2.7000e+01 3.0000e+00 1.6000e+03 1.0000e+01 5.0000e+00
  3.0000e+00]
 [1.0100e+03 5.0000e+01 7.0000e+00 5.0000e+03 3.0000e+01 8.0000e+00
  5.0000e+00]
 [1.0055e+03 3.4500e+01 3.4000e+00 2.1850e+03 1.2000e+01 4.5000e+00
  4.0000e+00]] 


 [1001   25    2 1200   10    3    5 1002   32    1  800    5    5    4
 1003 