In [1]:
import numpy as np

# Data structure:
# [patient_id, BP, Sugar, Cholesterol, HeartRate]

a= np.array([
    [201, 120,  90, 180, 72],
    [202, 135, 110, 220, 85],
    [203, 118,  95, 175, 70],
    [204, 145, 130, 240, 92],
    [205, 125, 100, 190, 78],
    [206, 138, 115, 210, 88]
])
print("\n", a[:,0], "\n")
print("\n", a[:,-1], "\n")
print("\n", a[3,1:], "\n")
print("\n", a.shape, "\n")


print("\n", np.sum(a[:,1:], axis=1), "\n")
print("\n", np.sum(a[:,1:], axis=0), "\n")


print("\n", np.mean(a[:,1:], axis=1), "\n")
print("\n", np.mean(a[:,1:], axis=0), "\n")


print("\n", np.max(a[:,1:]), "\n")
print("\n", np.min(a[:,1:]), "\n")


print("\n", a[(np.argmax(a[:,4])), 0], "\n")
print("\n", a[(np.argmin(a[:,1])), 0], "\n")


print("\n", a[a[:,3] > 200, 0], "\n")
print("\n", a[a[:,2] > 100], "\n")


print("\n", np.sum(a[:,1] > 130), "\n")


 [201 202 203 204 205 206] 


 [72 85 70 92 78 88] 


 [145 130 240  92] 


 (6, 5) 


 [462 550 458 607 493 551] 


 [ 781  640 1215  485] 


 [115.5  137.5  114.5  151.75 123.25 137.75] 


 [130.16666667 106.66666667 202.5         80.83333333] 


 240 


 70 


 204 


 203 


 [202 204 206] 


 [[202 135 110 220  85]
 [204 145 130 240  92]
 [206 138 115 210  88]] 


 3 



In [2]:
import numpy as np

# Data structure:
# [patient_id, BP, Sugar, Cholesterol, HeartRate]

a= np.array([
    [201, 120,  90, 180, 72],
    [202, 135, 110, 220, 85],
    [203, 118,  95, 175, 70],
    [204, 145, 130, 240, 92],
    [205, 125, 100, 190, 78],
    [206, 138, 115, 210, 88]
])


print("\n",a[np.sum(a[:,1:],axis=1)>540,0],"\n")

a0=a.copy()
a0[:,1:] += 10
print("\n",a0,"\n")

a1=a.copy()
a1[:,1] += 5
a1[:,2] += 10
a1[:,3] += 15
a1[:,4] += 2
print("\n",a1,"\n")


a2=a.copy().astype(float)
a2[:,1:] *= 1.10
print("\n",a2,"\n")


# Shape after extracting health metrics(removing id column and only keeping other values)
print("\n",a[:,1:].shape,"\n")


 [202 204 206] 


 [[201 130 100 190  82]
 [202 145 120 230  95]
 [203 128 105 185  80]
 [204 155 140 250 102]
 [205 135 110 200  88]
 [206 148 125 220  98]] 


 [[201 125 100 195  74]
 [202 140 120 235  87]
 [203 123 105 190  72]
 [204 150 140 255  94]
 [205 130 110 205  80]
 [206 143 125 225  90]] 


 [[201.  132.   99.  198.   79.2]
 [202.  148.5 121.  242.   93.5]
 [203.  129.8 104.5 192.5  77. ]
 [204.  159.5 143.  264.  101.2]
 [205.  137.5 110.  209.   85.8]
 [206.  151.8 126.5 231.   96.8]] 


 (6, 4) 



In [ ]:
import numpy as np

# Data structure:
# [patient_id, BP, Sugar, Cholesterol, HeartRate]

a= np.array([
    [201, 120,  90, 180, 72],
    [202, 135, 110, 220, 85],
    [203, 118,  95, 175, 70],
    [204, 145, 130, 240, 92],
    [205, 125, 100, 190, 78],
    [206, 138, 115, 210, 88]
])

print("\n",a[::-1],"\n")

print("\n",a[:,:-5:-1],"\n")

print("\n",a[np.argmax(np.sum(a[:,1:],axis=1)),0],"\n")

print("\n",a[np.argsort(a[:,4]),0],"\n")

# Both the methods add Columns

print("\n", np.column_stack((a, np.sum(a[:,1:], axis=1))).shape, "\n")

print("\n", np.hstack((a, np.sum(a[:,1:], axis=1).reshape(-1, 1))).shape, "\n")


# For rows

print("\n", np.vstack((a, np.mean(a, axis=0))), "\n")      # Full array with average row

print("\n", np.round(np.mean(a, axis=0), 2), "\n")         # Only the average row


# Replace values

print("\n", np.where(a[:,1:] < 100, 100, a[:,1:]), "\n")

print("\n", np.where(a[:,1:] > 220, 220, a[:,1:]), "\n")


# Top 3 IDs based on total health metrics

print("\n", a[np.argsort(np.sum(a[:,1:], axis=1))[-3:], 0], "\n")


 [[206 138 115 210  88]
 [205 125 100 190  78]
 [204 145 130 240  92]
 [203 118  95 175  70]
 [202 135 110 220  85]
 [201 120  90 180  72]] 


 [[ 72 180  90 120]
 [ 85 220 110 135]
 [ 70 175  95 118]
 [ 92 240 130 145]
 [ 78 190 100 125]
 [ 88 210 115 138]] 


 204 


 [203 201 205 202 206 204] 


 (6, 6) 


 (6, 6) 


 [[201.         120.          90.         180.          72.        ]
 [202.         135.         110.         220.          85.        ]
 [203.         118.          95.         175.          70.        ]
 [204.         145.         130.         240.          92.        ]
 [205.         125.         100.         190.          78.        ]
 [206.         138.         115.         210.          88.        ]
 [203.5        130.16666667 106.66666667 202.5         80.83333333]] 


 [203.5  130.17 106.67 202.5   80.83] 


 [[120 100 180 100]
 [135 110 220 100]
 [118 100 175 100]
 [145 130 240 100]
 [125 100 190 100]
 [138 115 210 100]] 


 [[120  90 180  72]
 [135 110 220  8