#### NumPy Array Operations

In [1]:
import numpy as np

### 1d Array

In [11]:
arr=np.arange(1,11)
print("Array\n",arr)
print("\nBasic Slicing\n",arr[0:8])
print("\nWith Step\n", arr[0:11:2])
print("\nNegative Slice\n", arr[-3])
print("\nNegative Slice2\n", arr[::-1])




Array
 [ 1  2  3  4  5  6  7  8  9 10]

Basic Slicing
 [1 2 3 4 5 6 7 8]

With Step
 [1 3 5 7 9]

Negative Slice
 8

Negative Slice2
 [10  9  8  7  6  5  4  3  2  1]


### 2d Array


In [4]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                 ])

print("Specific Element1", arr_2d[1,2])
print("Specific Element2", arr_2d[2,2])
print("Specific Element3", arr_2d[1,1])
print("Specific Element4", arr_2d[0,2])
print("Specific Element5", arr_2d[0,1])
print("Specific Element6", arr_2d[2,1])


print("\nEntire Row0",arr_2d[0])
print("Entire Row1",arr_2d[1])
print("Entire Row2",arr_2d[2])


print("\nEntire column0",arr_2d[:,0])
print("Entire column1",arr_2d[:,1])
print("Entire column2",arr_2d[:,2])


print("\n",arr_2d[0:2:1,0:2:1])







Specific Element1 6
Specific Element2 9
Specific Element3 5
Specific Element4 3
Specific Element5 2
Specific Element6 8

Entire Row0 [1 2 3]
Entire Row1 [4 5 6]
Entire Row2 [7 8 9]

Entire column0 [1 4 7]
Entire column1 [2 5 8]
Entire column2 [3 6 9]

 [[1 2]
 [4 5]]


### Sorting

In [15]:
unsorted=np.array([[3,1],
                   [1,2],
                   [2,3]])
print("Unsorted\n",unsorted)
print("\nSorted on row\n",np.sort(unsorted,axis=1))
print("\nSorted on column\n",np.sort(unsorted,axis=0))

Unsorted
 [[3 1]
 [1 2]
 [2 3]]

Sorted on row
 [[1 3]
 [1 2]
 [2 3]]

Sorted on column
 [[1 1]
 [2 2]
 [3 3]]


#### Filter

In [2]:
#1d array
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[a>3])
print('\n',a[a%2==0])
#arrayname[condition]

#2d array
a = np.array([
    [1,2,3],
    [4,5,6]
])

print("\n",a[a > 2])





[ 4  5  6  7  8  9 10]

 [ 2  4  6  8 10]

 [3 4 5 6]


#### mask-an array of True and False values

In [23]:
a=np.array([1,2,3,4,5])
mask=a>3
print(mask)

[False False False  True  True]


### Fancy Indexing Vs np.where()

In [ ]:
a=np.array([10,20,30,40,50]) # fancy indexing(selecting specific elements from array(no change in original array))
print("1d\n",a[[0,2,4]])


a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print("2d\n",a[[0,2]])
#2d arrays takes indexes of rows



#SELECTING SPECIFIC ELEMENTS
#************IMP********************

a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print("ELEMENt\n",a[[0,1,2],[2,1,0]])  # it take [[row],[columns]]=> meaning [0,2],[1,2],[2,0]=>[3],[5],[7]=>[3,5,7]


#fancy indexing creates copy not view(no affect in original array)

1d
 [10 30 50]
2d
 [[1 2 3]
 [7 8 9]]
ELEMENt
 [3 5 7]


#### np.where()

In [ ]:
a = np.array([1,2,3,4,5])

print(np.where(a > 3, 100, 0))
# (condition,if true replace it with this value here,else with this value

[  0   0   0 100 100]


In [4]:
#np.where()

a = np.array([1,2,3,4,5])
print(np.where(a%2==0,a,-1))



[-1  2 -1  4 -1]


### Adding and Removing 

In [ ]:
#np.concatenate((a,b))
a=np.array([1,2,3,4])
b=np.array([5,6])
print("Concatenate\n", np.concatenate((a,b)))

Concatenate
 [1 2 3 4 5 6]


In [12]:
#np.append(arrayname,value)

a=np.array([1,2,3,4])
b=np.append(a,5)
print("Single Value\n",b)



a=np.array([1,2,3,4])
b=np.append(a,[5,6,7])
print("\nMultiple Value\n",b)

Single Value
 [1 2 3 4 5]

Multiple Value
 [1 2 3 4 5 6 7]


In [ ]:
# Insert data at specific position
#np.insert(arrayname, index, value)


a = np.array([10, 20, 30])
b=np.insert(a,1,15)
print(b)

[10 15 20 30]


In [15]:
#Removing 
#np.delete(arraynaem, index)
a = np.array([10, 20, 30, 40])
b=np.delete(a,2)
print(b)

[10 20 40]


#### Adding Rows in 2d Array

In [ ]:
#np.vstack((arrayname,value))
a = np.array([[1, 2],
              [3, 4]])

new_row = np.array([5, 6])

b = np.vstack((a, new_row))
print(b)

[[1 2]
 [3 4]
 [5 6]]


#### Adding Columns in 2d Array

In [ ]:
# np.hstack((arrayname,value))
a=np.array([[1,2],
            [3,4]])
new_col=np.array([[5],
                  [6]])
b=np.hstack((a,new_col))
print(b)

[[1 2 5]
 [3 4 6]]


### Remove Rows and Column

In [19]:
a=np.array([[1,2],
            [3,4],
            [5,6]])

b=np.delete(a,1,axis=0)
print("Row Delete\n",b)



a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.delete(a, 1, axis=1)

print("Column Delete\n",b)

Row Delete
 [[1 2]
 [5 6]]
Column Delete
 [[1 3]
 [4 6]]
