#### NumPy Practice


In [ ]:
import numpy as np

In [ ]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

arr_2d=np.array([[1,2,3],
                 [4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
list=[1,2,3]
print(list*2)
#here whole list is multiplied by 2 


arr=np.array([1,2,3])
print(arr*2)
#here the elements are multiplied by 2

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
import time
start=time.time()
list=[]
for i in range(1000000):
    list.append(i*2)
print(time.time()-start)


start=time.time()
arr=np.arange(1000000)*2
print(time.time()-start)
#More Efficient





0.10722160339355469
0.004488468170166016


#### Creating Array From Scratch

In [11]:
Zeroes1=np.zeros((3,4))
print("\n",Zeroes1)


Zeroes2=np.zeros((3,3))
print("\n",Zeroes2)

Ones1=np.ones((2,3))
print("\n",Ones1)


Ones2=np.ones((2,2))
print("\n",Ones2)



full=np.full((2,3),7)
print("\n",full)


random=np.random.random((2,3))
print("\n",random)

seq=np.arange(0,11,2)
print("\n",seq)



 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]]

 [[1. 1.]
 [1. 1.]]

 [[7 7 7]
 [7 7 7]]

 [[0.71760216 0.95885239 0.12998344]
 [0.28166352 0.72799106 0.36257571]]

 [ 0  2  4  6  8 10]


### Vector, Matrix & Tensor Array

In [ ]:
vector=np.array([1,2,3,4])
print(vector)

matrix=np.array([[1,2],
                 [3,4]])
print("\n",matrix)


tensor=np.array([[[1,2],
                  [3,4],
                  [5,6],
                  [7,8]]])

tensor2=np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print("\n",tensor)
print("\n",tensor2)




[1 2 3 4]

 [[1 2]
 [3 4]]

 [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]

 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties


In [18]:
arr=np.array([[1,2],
              [3,4]])
print("shape",arr.shape)
print("dimensions",arr.ndim,"d")
print("size",arr.size)
print("DataType",arr.dtype)

shape (2, 2)
dimensions 2 d
size 4
DataType int64


### Array Reshaping

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("O\n",arr)

re=arr.reshape((3,2))# returs view (doesnt create copy(may affect original array))
print("R\n",re)

flat=re.flatten()
print("F\n",flat)
#returns copy(creates new array)
#changing in flatten array doesn't affect original array

ravel=re.ravel()
print("Ravel\n",ravel)
# returns view(original array), instead of copy whenever possible
#changing in ravel array may affect original array
#ravel() uses same memory
#Less memory used
#ravel() may sometimes create copy if needed internally.


# both flatten() and ravel() 
# convert multidimensional arrays into 1D arrays.

#Transpose

trans=re.T
print("T\n",trans)


O
 [[1 2 3]
 [4 5 6]]
R
 [[1 2]
 [3 4]
 [5 6]]
F
 [1 2 3 4 5 6]
Ravel
 [1 2 3 4 5 6]
T
 [[1 3 5]
 [2 4 6]]
