In [1]:
import numpy as np
import numpy.linalg as LA

#### Linear Algebra

In [2]:
# 2x + y = 8
# x + 3y = 13


A = np.array([[2,1],
              [1,3]])

b = np.array([8,13])

x = LA.solve(A,b)

print(x)

[2.2 3.6]


[2.2 3.6] here x=2.2 and y= 3.6

In [ ]:
# Matrix Rank - Rank tells how many independent rows/columns exist.

A = np.array([[1,2],
              [2,4]])

print(LA.matrix_rank(A))


1


In [ ]:
# Norm - Think of norm as matrix/vector length.(√(3²+4²)=5)


A = np.array([3,4])

print(LA.norm(A))


5.0


#### Random Module

In [5]:
#  Random Decimals

print(np.random.rand(5))

[0.6527724  0.26053944 0.37413606 0.02645747 0.67241132]


In [ ]:
#  Random Integers

print(np.random.randint(1,10,5))#5 random numbers from 1-9.

In [ ]:
# seed- Fixes randomness.

np.random.seed(1)

print(np.random.randint(1,10,5))#Every time same output.

[6 9 6 1 1]


In [ ]:
# Normal Distribution

print(np.random.normal(0,1,5))

[-1.601721   -1.47782957  0.48349585  0.18843661 -0.46468632]


In [11]:
# STACKING ARRAYS
# Stacking means combining multiple arrays together.
# Think of it as joining arrays either vertically
# (one below another) or horizontally (side by side).

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical Stack (adds rows)
print("Vertical Stack:")
print(np.vstack((a, b)))


# Horizontal Stack (adds columns/elements)
print("\nHorizontal Stack:")
print(np.hstack((a, b)))




# Column Stack
# Converts arrays into columns and joins them
print("\nColumn Stack:")
print(np.column_stack((a, b)))


Vertical Stack:
[[1 2 3]
 [4 5 6]]

Horizontal Stack:
[1 2 3 4 5 6]

Column Stack:
[[1 4]
 [2 5]
 [3 6]]


In [12]:
# SPLITTING ARRAYS
# Splitting is the opposite of stacking.
# It divides an array into smaller arrays.


a = np.array([1, 2, 3, 4, 5, 6])

# Split into 2 equal parts
print("Split:")
print(np.split(a, 2))



# Horizontal Split
# Splits columns

b = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("\nHorizontal Split:")
print(np.hsplit(b, 2))


# Vertical Split
# Splits rows

c = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

print("\nVertical Split:")
print(np.vsplit(c, 2))


Split:
[array([1, 2, 3]), array([4, 5, 6])]

Horizontal Split:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

Vertical Split:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
# HANDLING MISSING VALUES (NaN)
# NaN = Not a Number
#
# Used when data is missing.
#
# Common in CSV files, Excel files and datasets.



a = np.array([1, 2, np.nan, 4])

print("Array:")
print(a)



# Check Missing Values

print("\nCheck NaN:")
print(np.isnan(a))



# Normal Mean

print("\nNormal Mean:")
print(np.mean(a))

# Output:
# nan
#
# Because NumPy cannot calculate mean
# when NaN is present.


# Ignore NaN while calculating Mean

print("\nMean Ignoring NaN:")
print(np.nanmean(a))




# Ignore NaN while calculating Sum

print("\nSum Ignoring NaN:")
print(np.nansum(a))



# Ignore NaN while calculating Maximum

print("\nMaximum Ignoring NaN:")
print(np.nanmax(a))



# Ignore NaN while calculating Minimum

print("\nMinimum Ignoring NaN:")
print(np.nanmin(a))



Array:
[ 1.  2. nan  4.]

Check NaN:
[False False  True False]

Normal Mean:
nan

Mean Ignoring NaN:
2.3333333333333335

Sum Ignoring NaN:
7.0

Maximum Ignoring NaN:
4.0

Minimum Ignoring NaN:
1.0


#### Matrix Operations

In [14]:
# A Matrix is simply a 2D NumPy Array.
#
# Rows → Horizontal
# Columns → Vertical


A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


In [15]:
# MATRIX ADDITION
# Adds corresponding elements.

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A + B)


[[ 6  8]
 [10 12]]


In [16]:
#  MATRIX SUBTRACTION
# Subtracts corresponding elements.


A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A - B)



[[-4 -4]
 [-4 -4]]


In [17]:
# 3. SCALAR MULTIPLICATION
# Multiplies every element by a number.
#
# Scalar = Single Number

A = np.array([[1,2],[3,4]])

print(A * 2)


[[2 4]
 [6 8]]


In [18]:
#  ELEMENT-WISE MULTIPLICATION
# * operator performs element-wise multiplication
#
# NOT matrix multiplication.

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A * B)

# 1×5 = 5
# 2×6 = 12
# 3×7 = 21
# 4×8 = 32

[[ 5 12]
 [21 32]]


In [ ]:
# MATRIX MULTIPLICATION
# Use @ operator or np.matmul()
#
# Matrix multiplication follows:
#
# Row × Column


A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A @ B)



[[19 22]
 [43 50]]


In [ ]:
#  MATRIX TRANSPOSE
# Converts rows into columns
# and columns into rows.

A = np.array([[1,2],
              [3,4]])

print(A.T)


[[1 3]
 [2 4]]


In [21]:
# DETERMINANT
# Only for square matrices.
#
# For 2x2 Matrix:
#
# [[a b]
#  [c d]]
#
# Determinant = (a*d) - (b*c)
#
# Used to check whether inverse exists.


A = np.array([[1,2],
              [3,4]])

print(np.linalg.det(A))
# (1×4) - (2×3)
# = 4 - 6
# = -2

-2.0000000000000004


In [22]:
# INVERSE OF MATRIX
# Similar to division in matrix mathematics.
#
# Only possible if determinant != 0


A = np.array([[1,2],
              [3,4]])

print(np.linalg.inv(A))


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#  IDENTITY MATRIX
# Equivalent of number 1 in matrices.
#
# Main diagonal = 1
# Others = 0
#
# Multiplying by identity matrix
# does not change the matrix.


print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#  VERIFY INVERSE    ##########
# Matrix × Inverse
# = Identity Matrix


A = np.array([[1,2],
              [3,4]])

inverse = np.linalg.inv(A)

print(A @ inverse)


[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [25]:
# MATRIX RANK
# Rank tells how many independent
# rows or columns exist.
#
# If one row is a multiple of another,
# rank decreases.

A = np.array([
    [1,2],
    [2,4]
])

print(np.linalg.matrix_rank(A))


1


In [26]:
#  TRACE OF MATRIX
# Trace = Sum of diagonal elements


A = np.array([
    [1,2],
    [3,4]
])

print(np.trace(A))


5


In [27]:
# 15. DOT PRODUCT
# Dot Product works on vectors.
#
# Formula:
#
# (a1*b1)+(a2*b2)+(a3*b3)...

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

# (1×4)+(2×5)+(3×6)
# = 4+10+18
# = 32

32
