In [1]:
import numpy as np
import numpy.linalg as LA

#### Linear Algebra

In [2]:
# 2x + y = 8
# x + 3y = 13


A = np.array([[2,1],
              [1,3]])

b = np.array([8,13])

x = LA.solve(A,b)

print(x)

[2.2 3.6]


[2.2 3.6] here x=2.2 and y= 3.6

In [ ]:
# Matrix Rank - Rank tells how many independent rows/columns exist.

A = np.array([[1,2],
              [2,4]])

print(LA.matrix_rank(A))


1


In [ ]:
# Norm - Think of norm as matrix/vector length.(√(3²+4²)=5)


A = np.array([3,4])

print(LA.norm(A))


5.0


#### Random Module

In [5]:
#  Random Decimals

print(np.random.rand(5))

[0.6527724  0.26053944 0.37413606 0.02645747 0.67241132]


In [ ]:
#  Random Integers

print(np.random.randint(1,10,5))#5 random numbers from 1-9.

In [ ]:
# seed- Fixes randomness.

np.random.seed(1)

print(np.random.randint(1,10,5))#Every time same output.

[6 9 6 1 1]


In [ ]:
# Normal Distribution

print(np.random.normal(0,1,5))

[-1.601721   -1.47782957  0.48349585  0.18843661 -0.46468632]


In [11]:
# STACKING ARRAYS
# Stacking means combining multiple arrays together.
# Think of it as joining arrays either vertically
# (one below another) or horizontally (side by side).

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical Stack (adds rows)
print("Vertical Stack:")
print(np.vstack((a, b)))


# Horizontal Stack (adds columns/elements)
print("\nHorizontal Stack:")
print(np.hstack((a, b)))




# Column Stack
# Converts arrays into columns and joins them
print("\nColumn Stack:")
print(np.column_stack((a, b)))


Vertical Stack:
[[1 2 3]
 [4 5 6]]

Horizontal Stack:
[1 2 3 4 5 6]

Column Stack:
[[1 4]
 [2 5]
 [3 6]]


In [12]:
# SPLITTING ARRAYS
# Splitting is the opposite of stacking.
# It divides an array into smaller arrays.


a = np.array([1, 2, 3, 4, 5, 6])

# Split into 2 equal parts
print("Split:")
print(np.split(a, 2))



# Horizontal Split
# Splits columns

b = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("\nHorizontal Split:")
print(np.hsplit(b, 2))


# Vertical Split
# Splits rows

c = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

print("\nVertical Split:")
print(np.vsplit(c, 2))


Split:
[array([1, 2, 3]), array([4, 5, 6])]

Horizontal Split:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

Vertical Split:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [13]:
# 22. HANDLING MISSING VALUES (NaN)
# NaN = Not a Number
#
# Used when data is missing.
#
# Common in CSV files, Excel files and datasets.



a = np.array([1, 2, np.nan, 4])

print("Array:")
print(a)



# Check Missing Values

print("\nCheck NaN:")
print(np.isnan(a))



# Normal Mean

print("\nNormal Mean:")
print(np.mean(a))

# Output:
# nan
#
# Because NumPy cannot calculate mean
# when NaN is present.


# Ignore NaN while calculating Mean

print("\nMean Ignoring NaN:")
print(np.nanmean(a))




# Ignore NaN while calculating Sum

print("\nSum Ignoring NaN:")
print(np.nansum(a))



# Ignore NaN while calculating Maximum

print("\nMaximum Ignoring NaN:")
print(np.nanmax(a))



# Ignore NaN while calculating Minimum

print("\nMinimum Ignoring NaN:")
print(np.nanmin(a))



Array:
[ 1.  2. nan  4.]

Check NaN:
[False False  True False]

Normal Mean:
nan

Mean Ignoring NaN:
2.3333333333333335

Sum Ignoring NaN:
7.0

Maximum Ignoring NaN:
4.0

Minimum Ignoring NaN:
1.0
