In [1]:
import numpy as np

In [2]:
import numpy as np
arr_3d=np.array([[[1,2],
                  [3,4]],
                 [[5,6],
                  [7,8]],
                 [[9,10],
                  [11,12]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)
print(arr_3d.dtype)
print(arr_3d.size)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)
int64
12


In [3]:
a=np.zeros((2,3))
print(a)

b=np.ones((2,3))
print(b)


c=np.random.random((2,3))
print(c)


d=np.full((2,3),7)
print(d)

e=np.eye(3)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.31215749 0.17175637 0.52572687]
 [0.05282865 0.43000326 0.53458519]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
a = np.array([10,50,30])

print(a[np.argmax(a)])

50


In [5]:
a=np.arange(1,11)



print(a)
print(a[1])
print(a[0:5])
print(a[1:6:2])
print(a[-1])
print(a[::-1])
print(a[::-2])
print(a[::-3])



[ 1  2  3  4  5  6  7  8  9 10]
2
[1 2 3 4 5]
[2 4 6]
10
[10  9  8  7  6  5  4  3  2  1]
[10  8  6  4  2]
[10  7  4  1]


In [6]:
a=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                 ])

print(a)
print(a[0:,1:])
print(a[1:2,1:3])
print(a[:,1:2])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[5 6]]
[[2]
 [5]
 [8]]


In [7]:
a=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                 ])

print(a[0:1,0:3])

[[1 2 3]]


In [8]:
a=np.array([[3,1],
            [1,2],
            [2,3]])

print(np.sort(a,axis=0))
print(np.sort(a,axis=1))


[[1 1]
 [2 2]
 [3 3]]
[[1 3]
 [1 2]
 [2 3]]


In [9]:
import numpy as np

# Data structure:
# [store_id, 2021, 2022, 2023, 2024]

a = np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])



print("\n",a[:,:])#Q1. Print the entire array.
print("\n",a[:,0:1])#Q2. Print only the store IDs.
print("\n",a[:,0])#Q2. Print only the store IDs.
print("\n",a[:,-1])#Q3. Print 2024 sales of all stores.
print("\n",a[2,1:])#Q4. Print sales of Store 3.
print("\n",a.shape)#Q5. Find shape of array.
print("\n",a.ndim)#Q6. Find number of dimensions.
print("\n",a.size)#Q7. Find total number of elements.
print("\n",a.dtype)#Q8. Find datatype of array.




 [[     1 100000 120000 150000 180000]
 [     2  90000 110000 130000 170000]
 [     3 150000 170000 200000 240000]
 [     4 130000 145000 175000 210000]
 [     5 110000 125000 155000 190000]
 [     6 160000 190000 220000 260000]]

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

 [1 2 3 4 5 6]

 [180000 170000 240000 210000 190000 260000]

 [150000 170000 200000 240000]

 (6, 5)

 2

 30

 int64


In [10]:
import numpy as np

# Data structure:
# [store_id, 2021, 2022, 2023, 2024]

a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])


print("\n",np.sum(a[:,1:],axis=1))#Q9. Find total sales of each store across all years.

print("\n",np.sum(a[:,1:],axis=0))#Q10. Find total sales for each year.

print("\n",np.mean(a[:,1:],axis=1))#Q11 Average sales of each store

print("\n",np.mean(a[:,1:],axis=0))#Q11 Average sales of each year

print("\n",np.max(a[:,:]))#Q13 Maximum sale value

print("\n",np.min(a[:,1:]))#Q14 Minimum sale value

print(f"\n store-ID={(np.argmax(a[:,4]))+1},","Store Index=",np.argmax(a[:,4]))#Q15. Find store with highest 2024 sales

print(f"\n store-ID={(np.argmin(a[:,1]))+1},","Store Index=",np.argmin(a[:,1]))#Q15. Find store with lowest 2021 sales

print("\n",a[a[:,4]>200000,0])#Q17 Stores whose 2024 sales > 200000

print("\n",a[a[:,3]>180000,0])#Q18. Print storeids where 2023 sales exceed 180000.
print("\n",a[a[:,3]>180000])#Q18. Print rows where 2023 sales exceed 180000.


print(np.sum(a[:,4]>200000))#Q19 Count stores having 2024 sales > 200000


 [550000 500000 760000 660000 580000 830000]

 [ 740000  860000 1030000 1250000]

 [137500. 125000. 190000. 165000. 145000. 207500.]

 [123333.33333333 143333.33333333 171666.66666667 208333.33333333]

 260000

 90000

 store-ID=6, Store Index= 5

 store-ID=2, Store Index= 1

 [3 4 6]

 [3 6]

 [[     3 150000 170000 200000 240000]
 [     6 160000 190000 220000 260000]]
3


In [11]:
import numpy as np#Q21 Increase all sales values by 10000

# Data structure:
# [store_id, 2021, 2022, 2023, 2024]

a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])



new_data = a.copy()

new_data[:, 1:] = new_data[:, 1:] + 10000

print(new_data)

[[     1 110000 130000 160000 190000]
 [     2 100000 120000 140000 180000]
 [     3 160000 180000 210000 250000]
 [     4 140000 155000 185000 220000]
 [     5 120000 135000 165000 200000]
 [     6 170000 200000 230000 270000]]


In [12]:
import numpy as np#Q22 Add different amounts per year

# Data structure:
# [store_id, 2021, 2022, 2023, 2024]

a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])


newdata=a.copy()
newdata[:,1]=newdata[:,1]+5000
newdata[:,2]=newdata[:,2]+10000
newdata[:,3]=newdata[:,3]+15000
newdata[:,4]=newdata[:,4]+20000


print(newdata)

[[     1 105000 130000 165000 200000]
 [     2  95000 120000 145000 190000]
 [     3 155000 180000 215000 260000]
 [     4 135000 155000 190000 230000]
 [     5 115000 135000 170000 210000]
 [     6 165000 200000 235000 280000]]


In [13]:
import numpy as np# Growth

# Data structure:
# [store_id, 2021, 2022, 2023, 2024]

a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])


newdata=a.copy()
newdata[:,1]=newdata[:,1]*1.05
newdata[:,2]=newdata[:,2]*1.08
newdata[:,3]=newdata[:,3]*1.10
newdata[:,4]=newdata[:,4]*1.12


print(newdata)

[[     1 105000 129600 165000 201600]
 [     2  94500 118800 143000 190400]
 [     3 157500 183600 220000 268800]
 [     4 136500 156600 192500 235200]
 [     5 115500 135000 170500 212800]
 [     6 168000 205200 242000 291200]]


In [14]:
import numpy as np#QQ23 Apply 10% growth

# Data structure:
# [store_id, 2021, 2022, 2023, 2024]

a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])




new_data = a.copy()

new_data[:, 1:] = (new_data[:, 1:]*1.10)

print(new_data)

[[     1 110000 132000 165000 198000]
 [     2  99000 121000 143000 187000]
 [     3 165000 187000 220000 264000]
 [     4 143000 159500 192500 231000]
 [     5 121000 137500 170500 209000]
 [     6 176000 209000 242000 286000]]


In [15]:
import numpy as np#Q25 Shape after extracting sales columns (remove the id column)

# Data structure:
# [store_id, 2021, 2022, 2023, 2024]

a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])

b=a[:,1:]
print(b.shape)


print(a[0:3,:])#Q26 First 3 stores

print("\n",a[4:6,:])#Q27 Last 2 stores

c=a[:,2:4]#Q28 Shape of 2022 and 2023 columns
print(c.shape)


print(a[::-1])#Q29 Reverse stores

newdata=a.copy()#Q30 Reverse years
newdata[:,1:]=a[:,1:][:,::-1]
print("\n",newdata)

(6, 4)
[[     1 100000 120000 150000 180000]
 [     2  90000 110000 130000 170000]
 [     3 150000 170000 200000 240000]]

 [[     5 110000 125000 155000 190000]
 [     6 160000 190000 220000 260000]]
(6, 2)
[[     6 160000 190000 220000 260000]
 [     5 110000 125000 155000 190000]
 [     4 130000 145000 175000 210000]
 [     3 150000 170000 200000 240000]
 [     2  90000 110000 130000 170000]
 [     1 100000 120000 150000 180000]]

 [[     1 180000 150000 120000 100000]
 [     2 170000 130000 110000  90000]
 [     3 240000 200000 170000 150000]
 [     4 210000 175000 145000 130000]
 [     5 190000 155000 125000 110000]
 [     6 260000 220000 190000 160000]]


In [16]:

# Data structure:
# [store_id, 2021, 2022, 2023, 2024]

a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])


growth=np.diff(a[:,1:],axis=1)#Q31 Year-wise growth
print(growth)


g=(a[:,4]-a[:,3])/a[:,3] *100 #Q32 Percentage growth from 2023 → 2024
print(g)


hs=np.sum(a[:,1:],axis=1) #Q33 Store with highest total sales
print("storeid ",a[np.argmax(hs),0])

[[20000 30000 30000]
 [20000 20000 40000]
 [20000 30000 40000]
 [15000 30000 35000]
 [15000 30000 35000]
 [30000 30000 40000]]
[20.         30.76923077 20.         20.         22.58064516 18.18181818]
storeid  6


In [17]:

# Data structure:Q34 Stores sorted by 2024 sales
# [store_id, 2021, 2022, 2023, 2024]

a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])

print(a[np.argsort(a[:,4]), 0])

[2 1 5 4 3 6]


In [18]:
#Q35 Stores sorted by total sales
a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])


ts=np.sum(a[:,1:],axis=1)
print(a[np.argsort(ts),0])


[2 1 5 4 3 6]


In [19]:
#Q36 Shape after adding total sales column (add ne clumn of total sales)
a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])
ts=np.sum(a[:,1:],axis=1)

print(ts)
ts=ts.reshape(-1,1)

n=np.hstack((a,ts))
print(n.shape)

[550000 500000 760000 660000 580000 830000]
(6, 6)


In [20]:
a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])

avg=np.mean(a[:,1:],axis=0)
print(avg)
avg_row = np.insert(avg, 0, 0)   # add placeholder for store_id
n=np.vstack((a,avg_row))
print(n.shape)

[123333.33333333 143333.33333333 171666.66666667 208333.33333333]
(7, 5)


In [21]:
a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])

print(np.where(a[:,1:]<120000,120000,a[:,1:]))
print("\n",np.where(a[:,1:]>220000,220000,a[:,1:]))



[[120000 120000 150000 180000]
 [120000 120000 130000 170000]
 [150000 170000 200000 240000]
 [130000 145000 175000 210000]
 [120000 125000 155000 190000]
 [160000 190000 220000 260000]]

 [[100000 120000 150000 180000]
 [ 90000 110000 130000 170000]
 [150000 170000 200000 220000]
 [130000 145000 175000 210000]
 [110000 125000 155000 190000]
 [160000 190000 220000 220000]]


In [22]:
a= np.array([
    [1, 100000, 120000, 150000, 180000],
    [2,  90000, 110000, 130000, 170000],
    [3, 150000, 170000, 200000, 240000],
    [4, 130000, 145000, 175000, 210000],
    [5, 110000, 125000, 155000, 190000],
    [6, 160000, 190000, 220000, 260000]
])

ts=np.sum(a[:,1:],axis=1)

print(a[np.argsort(ts)[-3:][::-1]])

[[     6 160000 190000 220000 260000]
 [     3 150000 170000 200000 240000]
 [     4 130000 145000 175000 210000]]
