In [1]:
import numpy as np


In [3]:
a = np.array([10,15,20,25])
print(a[a%10==0])



[10 20]


In [ ]:
a=np.array([[1,4,6,8,2]])
mask=a>5
print(a[mask])

[6 8]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])

print(a[a>2])

[3 4 5]


In [7]:
a=np.array([4,11,7,15,2])
mask=a<10
print(a[mask])

[4 7 2]


In [6]:
a=np.array([[3,5,6,9,10,12,15]])
mask=a%3==0
print(a[mask])

[ 3  6  9 12 15]


In [9]:
a=np.array([10,20,30,40,50])
print(a[[0,2,4]])

[10 30 50]


In [10]:
a=np.array([
 [1,2],
 [3,4],
 [5,6]
])

print(a[[0,2]])

[[1 2]
 [5 6]]


In [ ]:
a=np.array([
 [1,2,3],
 [4,5,6],
 [7,8,9]
])

print(a[[0,1,2],[1,2,0]])

[2 6 7]


In [2]:
a=np.array([1,6,3,8,2])
print(np.where(a>5,100,0))

[  0 100   0 100   0]


In [4]:
a=np.array([1,2,3,4,5,6])
print(np.where(a%2==0,a,-1))

[-1  2 -1  4 -1  6]


In [5]:
a=np.array([-3,5,-1,7,0])
print(np.where(a<0,0,a))

[0 5 0 7 0]


In [6]:
a=np.array([3,5,9,10,12])
print(np.where(a%3==0,999,a))

[999   5 999  10 999]


In [7]:
a=np.array([4,11,7,15,20])
print(np.where(a<10,"small","big"))

['small' 'big' 'small' 'big' 'big']


In [2]:
a=np.array([1,6,2,8,3])
print(np.where(a>5,a,a*10))

[10  6 20  8 30]


In [5]:
a=np.array([[1,2],
            [3,4]])
new_row=np.array([5,6])
b=np.vstack((a,new_row))
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [6]:
a=np.array([[10,20],
            [30,40]])
new_col=np.array([[50],
                  [60]])

b=np.hstack((a,new_col))
print(b)

[[10 20 50]
 [30 40 60]]


In [9]:
a=np.array([[1,2],
            [3,4],
            [5,6]])
d=np.delete(a,2,axis=0)
print(d)


[[1 2]
 [3 4]]


In [12]:
a=np.array([[7,8,9],
            [1,2,3]])
d=np.delete(a,0,axis=1)
print(d)

[[8 9]
 [2 3]]


In [13]:
a=np.array([[1,2],
            [3,4]])
b=np.append(a,[[5,6],
             [7,8]])
print(b)

[1 2 3 4 5 6 7 8]


In [15]:
a=np.arange(1,10).reshape(3,3)

n=np.vstack((a,[0,0,0]))
r=np.delete(n,1,axis=0)
print(r)

[[1 2 3]
 [7 8 9]
 [0 0 0]]


In [17]:
a = np.array([[1,2,3],
              [4,5,6]])
nc=np.hstack((a,[[7],
              [8]]))
print(nc)


[[1 2 3 7]
 [4 5 6 8]]


In [18]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

r=np.delete(a,1,axis=1)
print(r)

[[1 3]
 [4 6]
 [7 9]]


In [19]:
a=np.array([[1,2,3],
            [4,5,6]])

nr=np.vstack(([0,0,0],a))
print(nr)

[[0 0 0]
 [1 2 3]
 [4 5 6]]


In [20]:
a=np.array([[1,2],
            [0,0],
            [3,4]])

r=np.delete(a,1,axis=0)
print(r)

[[1 2]
 [3 4]]


In [29]:
a=np.array([[1,2],
            [3,4]])

nc = np.insert(a, 1, [9,9], axis=1)

print(nc)

[[1 9 2]
 [3 9 4]]


In [30]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])

dc1=np.delete(a,0,axis=1)
dc2=np.delete(dc1,2,axis=1)
print(dc2)

[[2 3]
 [6 7]]
