In [1]:
import numpy as np


In [3]:
a = np.array([10,15,20,25])
print(a[a%10==0])



[10 20]


In [ ]:
a=np.array([[1,4,6,8,2]])
mask=a>5
print(a[mask])

[6 8]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])

print(a[a>2])

[3 4 5]


In [7]:
a=np.array([4,11,7,15,2])
mask=a<10
print(a[mask])

[4 7 2]


In [6]:
a=np.array([[3,5,6,9,10,12,15]])
mask=a%3==0
print(a[mask])

[ 3  6  9 12 15]


In [9]:
a=np.array([10,20,30,40,50])
print(a[[0,2,4]])

[10 30 50]


In [10]:
a=np.array([
 [1,2],
 [3,4],
 [5,6]
])

print(a[[0,2]])

[[1 2]
 [5 6]]


In [ ]:
a=np.array([
 [1,2,3],
 [4,5,6],
 [7,8,9]
])

print(a[[0,1,2],[1,2,0]])

[2 6 7]


In [2]:
a=np.array([1,6,3,8,2])
print(np.where(a>5,100,0))

[  0 100   0 100   0]


In [4]:
a=np.array([1,2,3,4,5,6])
print(np.where(a%2==0,a,-1))

[-1  2 -1  4 -1  6]


In [5]:
a=np.array([-3,5,-1,7,0])
print(np.where(a<0,0,a))

[0 5 0 7 0]


In [6]:
a=np.array([3,5,9,10,12])
print(np.where(a%3==0,999,a))

[999   5 999  10 999]


In [7]:
a=np.array([4,11,7,15,20])
print(np.where(a<10,"small","big"))

['small' 'big' 'small' 'big' 'big']


In [ ]:
a=np.array([1,6,2,8,3])
print(np.where(a>5,a,a*10))

[10  6 20  8 30]


: 