### Dataset: Gym Membership Analytics

In [1]:
import numpy as np

# Columns:
# [Member_ID, Age, Membership_Type,
#  Monthly_Fee, Months_Joined,
#  Trainer_Fee, Attendance_Days,
#  Rating]

a = np.array([
    [2001, 22, 1, 1500, 12, 500, 22, 4],
    [2002, 35, 2, 2500, 8, 1000, 18, 5],
    [2003, 28, 1, 1500, 6, 500, 15, 3],
    [2004, 45, 3, 3500, 10, 1500, 25, 5],
    [2005, 31, 2, 2500, 5, 1000, 12, 4],
    [2006, 26, 1, 1500, 9, 500, 20, 2],
    [2007, 39, 3, 3500, 7, 1500, 27, 5],
    [2008, 29, 2, 2500, 4, 1000, 10, 3],
    [2009, 50, 3, 3500, 12, 1500, 30, 4],
    [2010, 23, 1, 1500, 11, 500, 24, 5],
    [2011, 37, 2, 2500, 6, 1000, 14, 2],
    [2012, 42, 3, 3500, 8, 1500, 26, 5]
])

In [2]:
# Q1. Total Membership Fee Collected
tmf=np.sum(a[:,3]*a[:,4])# Total membership fee
print(tmf)

244000


In [3]:
# Q2. Average Age Of Members

aa=np.mean(a[:,1]) # Average age
print(aa)



33.916666666666664


In [4]:
# Q3. Maximum Attendance Days

mad=np.max(a[:,-2])# maximum attendance days
print(mad)

30


In [5]:
# Q4. Count Members With Rating 5

mr=a[:,-1]==5#members rating
print(np.sum(mr))

5


In [6]:
# Q5. Members Attending More Than 20 Days

ar=a[a[:,-2]>20]
print(ar)

[[2001   22    1 1500   12  500   22    4]
 [2004   45    3 3500   10 1500   25    5]
 [2007   39    3 3500    7 1500   27    5]
 [2009   50    3 3500   12 1500   30    4]
 [2010   23    1 1500   11  500   24    5]
 [2012   42    3 3500    8 1500   26    5]]


In [7]:
# Q6. Create Revenue Column

r=(a[:,3]+a[:,5])*a[:,4]#revenue
rc=np.column_stack((a,r))# revenue coolumn
print(rc)
print(rc.shape)

[[ 2001    22     1  1500    12   500    22     4 24000]
 [ 2002    35     2  2500     8  1000    18     5 28000]
 [ 2003    28     1  1500     6   500    15     3 12000]
 [ 2004    45     3  3500    10  1500    25     5 50000]
 [ 2005    31     2  2500     5  1000    12     4 17500]
 [ 2006    26     1  1500     9   500    20     2 18000]
 [ 2007    39     3  3500     7  1500    27     5 35000]
 [ 2008    29     2  2500     4  1000    10     3 14000]
 [ 2009    50     3  3500    12  1500    30     4 60000]
 [ 2010    23     1  1500    11   500    24     5 22000]
 [ 2011    37     2  2500     6  1000    14     2 21000]
 [ 2012    42     3  3500     8  1500    26     5 40000]]
(12, 9)


In [8]:
# Q7. Member Generating Highest Revenue

r=(a[:,3]+a[:,5])*a[:,4]
mhr=np.argmax(r)# member highest revenue
print(a[mhr])
print(max(r))# maximum revenue


[2009   50    3 3500   12 1500   30    4]
60000


In [9]:
# Q8. Total Gym Revenue

r=(a[:,3]+a[:,5])*a[:,4]
gr=np.sum(r)# gym revenue
print(gr)

341500


In [10]:
# Q9. Average Rating Per Membership Type

for cat in np.unique(a[:,2]):
    rows = a[a[:,2] == cat]
    avg_rating = np.mean(rows[:,-1])
    print(f"Membership Type {cat} -> {avg_rating}")

Membership Type 1 -> 3.5
Membership Type 2 -> 3.5
Membership Type 3 -> 4.75


In [11]:
# Q10. Age > Average Age AND Rating < Average Rating
c=(a[:,1]>np.mean(a[:,1])) &  (a[:,-1]<np.mean(a[:,-1]))
print(a[c])

[[2011   37    2 2500    6 1000   14    2]]


In [12]:
# Q11. Top 3 Members By Revenue

r=(a[:,3]+a[:,5])*a[:,4]

sr=np.argsort(r) # sorted revenue
print(a[sr[-1:-4:-1]])
print(np.sort(r)[-3:])


# print(a[np.argsort(r)[::-1][:3]]) another approach for top 3


[[2009   50    3 3500   12 1500   30    4]
 [2004   45    3 3500   10 1500   25    5]
 [2012   42    3 3500    8 1500   26    5]]
[40000 50000 60000]


In [13]:
# Q12. Membership Type Generating Maximum Revenue

r=(a[:,3]+a[:,5])*a[:,4]
max_rev = 0
best_type = None

for cat in np.unique(a[:,2]):
    total_rev = np.sum(r[a[:,2] == cat])

    if total_rev > max_rev:
        max_rev = total_rev
        best_type = cat

print(f"Membership Type {best_type} -> {max_rev}")    
    
    

Membership Type 3 -> 185000


In [14]:
# Q13. Members With Revenue Above Average Revenue
r=(a[:,3]+a[:,5])*a[:,4]
aar=r>np.mean(r)#above avg revenue 
print(a[aar])

avg=np.mean(r)# avg revenue
print(avg)

[[2004   45    3 3500   10 1500   25    5]
 [2007   39    3 3500    7 1500   27    5]
 [2009   50    3 3500   12 1500   30    4]
 [2012   42    3 3500    8 1500   26    5]]
28458.333333333332


In [15]:
#Q14. Create Performance Status Column
att = a[:,-2]

status = np.where(att >= 25, 3,
         np.where(att >= 15, 2, 1))

sc=np.column_stack((a,status))

print(status)
print(sc)

[2 2 2 3 1 2 3 1 3 2 1 3]
[[2001   22    1 1500   12  500   22    4    2]
 [2002   35    2 2500    8 1000   18    5    2]
 [2003   28    1 1500    6  500   15    3    2]
 [2004   45    3 3500   10 1500   25    5    3]
 [2005   31    2 2500    5 1000   12    4    1]
 [2006   26    1 1500    9  500   20    2    2]
 [2007   39    3 3500    7 1500   27    5    3]
 [2008   29    2 2500    4 1000   10    3    1]
 [2009   50    3 3500   12 1500   30    4    3]
 [2010   23    1 1500   11  500   24    5    2]
 [2011   37    2 2500    6 1000   14    2    1]
 [2012   42    3 3500    8 1500   26    5    3]]


In [16]:
# Q15. Correlation Matrix @@
corr = np.corrcoef(
    [a[:,1], a[:,3], a[:,6], a[:,7]]
)

print(np.round(corr, 2))
print(corr.shape)


[[1.   0.92 0.5  0.31]
 [0.92 1.   0.45 0.46]
 [0.5  0.45 1.   0.57]
 [0.31 0.46 0.57 1.  ]]
(4, 4)


In [17]:
# Q16. Normalize @@

cols = a[:, [3,5,6]]
norm=(cols-np.min(cols,axis=0))/(np.max(cols,axis=0)-np.min(cols,axis=0))
print(np.round(norm,2))

[[0.   0.   0.6 ]
 [0.5  0.5  0.4 ]
 [0.   0.   0.25]
 [1.   1.   0.75]
 [0.5  0.5  0.1 ]
 [0.   0.   0.5 ]
 [1.   1.   0.85]
 [0.5  0.5  0.  ]
 [1.   1.   1.  ]
 [0.   0.   0.7 ]
 [0.5  0.5  0.2 ]
 [1.   1.   0.8 ]]


In [18]:
#Q17. Revenue Closest To Average Revenue
r=(a[:,3]+a[:,5])*a[:,4]

avg_r=np.mean(r)

rcar=np.argmin(np.abs(r-avg_r))
print(a[rcar])
print(r[rcar])



[2002   35    2 2500    8 1000   18    5]
28000


In [19]:
#Q18. Revenue Contribution %
r=(a[:,3]+a[:,5])*a[:,4]

tr=np.sum(r)

for cat in np.unique(a[:,2]):
    category_rev = np.sum(r[a[:,2] == cat])
    
    contri=(category_rev/tr)*100
    print(f"Type {cat} -> {contri:.2f}%")
    

Type 1 -> 22.25%
Type 2 -> 23.57%
Type 3 -> 54.17%


In [20]:
# Q19. Attendance > Average Attendance AND Revenue > Average Revenue
r=(a[:,3]+a[:,5])*a[:,4]

q=(a[:,6]>np.mean(a[:,6])) & (r>np.mean(r))

print(a[q])

[[2004   45    3 3500   10 1500   25    5]
 [2007   39    3 3500    7 1500   27    5]
 [2009   50    3 3500   12 1500   30    4]
 [2012   42    3 3500    8 1500   26    5]]


In [21]:
r=(a[:,3]+a[:,5])*a[:,4]

s=(r*(a[:,-1]))/(a[:,-2]+1)



print(np.round(s,2))# score



bm=np.argmax(s)# Best Member
print(a[bm])
print(s[bm])



wm=np.argmin(s)# worst member
print(a[wm])
print(s[wm])



top5 = np.argsort(s)[-5:][::-1]

print(a[top5])

for i in top5:
    print(s[i])

[4173.91 7368.42 2250.   9615.38 5384.62 1714.29 6250.   3818.18 7741.94
 4400.   2800.   7407.41]
[2004   45    3 3500   10 1500   25    5]
9615.384615384615
[2006   26    1 1500    9  500   20    2]
1714.2857142857142
[[2004   45    3 3500   10 1500   25    5]
 [2009   50    3 3500   12 1500   30    4]
 [2012   42    3 3500    8 1500   26    5]
 [2002   35    2 2500    8 1000   18    5]
 [2007   39    3 3500    7 1500   27    5]]
9615.384615384615
7741.935483870968
7407.407407407408
7368.421052631579
6250.0
