In [1]:
import numpy as np

# Columns:
# [Emp_ID, Age, Department,
#  Experience_Years, Base_Salary,
#  Bonus, Performance_Rating,
#  Projects_Completed]

a = np.array([
    [3001, 24, 1,  2, 30000,  5000, 4, 3],
    [3002, 35, 2,  8, 60000, 12000, 5, 8],
    [3003, 29, 3,  4, 45000,  8000, 3, 5],
    [3004, 41, 1, 12, 80000, 20000, 5,10],
    [3005, 31, 2,  6, 55000, 10000, 4, 6],
    [3006, 27, 3,  3, 40000,  7000, 2, 4],
    [3007, 45, 1, 15, 90000, 25000, 5,12],
    [3008, 30, 2,  5, 50000,  9000, 3, 5],
    [3009, 50, 3, 20,100000, 30000, 4,15],
    [3010, 26, 1,  3, 35000,  6000, 5, 4],
    [3011, 38, 2, 10, 70000, 15000, 2, 7],
    [3012, 43, 3, 14, 85000, 22000, 5,11]
])

In [2]:
# Q1. Total Monthly Salary Paid

tmsp=np.sum(a[:,4])
print(tmsp)

740000


In [3]:
# Q2. Average Employee Age
aea=np.mean(a[:,1])
print(aea)

34.916666666666664


In [6]:
# Q3. Highest Base Salary\
    
hbs=np.max(a[:,4])
print(hbs)

100000


In [13]:
# Q4. Count Employees With Rating 5
er=a[:,6]
r5=(er)==5
print(np.sum(r5))

5


In [10]:
# Q5. Employees Completing More Than 8 Projects

pc=a[:,7]
p8=pc>8
print(a[p8])
print(np.sum(p8))

[[  3004     41      1     12  80000  20000      5     10]
 [  3007     45      1     15  90000  25000      5     12]
 [  3009     50      3     20 100000  30000      4     15]
 [  3012     43      3     14  85000  22000      5     11]]
4


In [15]:
# Q6. Create Annual Compensation Column

ac=(a[:,4]+a[:,5])*12
print(ac)

acc=np.column_stack((ac,a))
print(acc)

[ 420000  864000  636000 1200000  780000  564000 1380000  708000 1560000
  492000 1020000 1284000]
[[ 420000    3001      24       1       2   30000    5000       4       3]
 [ 864000    3002      35       2       8   60000   12000       5       8]
 [ 636000    3003      29       3       4   45000    8000       3       5]
 [1200000    3004      41       1      12   80000   20000       5      10]
 [ 780000    3005      31       2       6   55000   10000       4       6]
 [ 564000    3006      27       3       3   40000    7000       2       4]
 [1380000    3007      45       1      15   90000   25000       5      12]
 [ 708000    3008      30       2       5   50000    9000       3       5]
 [1560000    3009      50       3      20  100000   30000       4      15]
 [ 492000    3010      26       1       3   35000    6000       5       4]
 [1020000    3011      38       2      10   70000   15000       2       7]
 [1284000    3012      43       3      14   85000   22000       5      11]]


In [22]:
# Q7. Employee With Highest Annual Compensation

ac=(a[:,4]+a[:,5])*12
print(np.max(ac))
print(a[np.argmax(ac)])

1560000
[  3009     50      3     20 100000  30000      4     15]


In [23]:
# Q8. Total Annual Compensation
ac=(a[:,4]+a[:,5])*12
print(np.sum(ac))




10908000


In [28]:
# Q9. Average Rating Per Department

for cat in np.unique(a[:,2]):
    avg_rating=np.mean(a[a[:,2]==cat,6])
    print(f"Department {cat}: {avg_rating}")

Department 1: 4.75
Department 2: 3.5
Department 3: 3.5


In [30]:
# Q10. Age > Average Age AND Rating < Average Rating

c=(a[:,1]>np.mean(a[:,1])) & (a[:,6]<np.mean(a[:,6]))
print(a[c])

[[ 3011    38     2    10 70000 15000     2     7]]


In [34]:
# Q11. Top 3 Employees By Compensation

ac=(a[:,4]+a[:,5])*12
sac=np.argsort(ac)
top3=sac[-1:-4:-1]
print(a[top3])
print(ac[top3])

[[  3009     50      3     20 100000  30000      4     15]
 [  3007     45      1     15  90000  25000      5     12]
 [  3012     43      3     14  85000  22000      5     11]]
[1560000 1380000 1284000]


In [37]:
# Q12. Department Generating Highest Compensation Cost

ac=(a[:,4]+a[:,5])*12

for cat in np.unique(a[:,2]):
    comp=np.sum(ac[a[:,2]==cat])
    print(f"Department {cat}: {comp}")
    
    
ac = (a[:,4] + a[:,5]) * 12

max_cost = 0
best_dept = None

for dept in np.unique(a[:,2]):
    total_cost = np.sum(ac[a[:,2] == dept])

    if total_cost > max_cost:
        max_cost = total_cost
        best_dept = dept

print(f"Department {best_dept} -> {max_cost}")
    

Department 1: 3492000
Department 2: 3372000
Department 3: 4044000
Department 3 -> 4044000


In [39]:
# Q13. Employees Above Average Compensation

ac = (a[:,4] + a[:,5]) * 12
avg_ac=np.mean(ac)

print(a[ac>avg_ac])


[[  3004     41      1     12  80000  20000      5     10]
 [  3007     45      1     15  90000  25000      5     12]
 [  3009     50      3     20 100000  30000      4     15]
 [  3011     38      2     10  70000  15000      2      7]
 [  3012     43      3     14  85000  22000      5     11]]


In [43]:
# Q14. Create Performance Level

pro=a[:,-1]

d=np.where(pro>=10,3,
           np.where (pro>=5,2,1))
print(d)

[1 2 2 3 2 1 3 2 3 1 2 3]


In [46]:
# Q15. Correlation Matrix

col=(a[:,1], a[:,4], a[:,6], a[:,7])
corr=np.corrcoef(col)

print(corr)
print(corr.shape)

[[1.         0.9961311  0.33363601 0.98409639]
 [0.9961311  1.         0.32677223 0.9752622 ]
 [0.33363601 0.32677223 1.         0.42633611]
 [0.98409639 0.9752622  0.42633611 1.        ]]
(4, 4)


In [ ]:
# Normalise 

In [ ]:
# Q17. Employee Closest To Average Compensation
ac = (a[:,4] + a[:,5]) * 12

aac=np.mean(ac)
f=np.argmin(np.abs(ac-aac))
print(a[f])
print(ac[f])

[ 3002    35     2     8 60000 12000     5     8]
864000


In [ ]:
# Q18. Compensation Contribution %
ac = (a[:,4] + a[:,5]) * 12

tc=np.sum(ac)

for cat in np.unique(a[:,2]):
    d_comp = np.sum(ac[a[:,2] == cat])
    
    contri=(d_comp/tc)*100

    print(f"Department {cat}={contri}")


Department 1=32.01320132013201
Department 2=30.913091309130913
Department 3=37.073707370737075


In [56]:
# Q19. Projects > Average Projects AND Compensation > Average Compensation

ac = (a[:,4] + a[:,5]) * 12

z=(a[:,7]>np.mean(a[:,7])) & (ac>np.mean(ac))
print(a[z])
print(ac[z])

[[  3004     41      1     12  80000  20000      5     10]
 [  3007     45      1     15  90000  25000      5     12]
 [  3009     50      3     20 100000  30000      4     15]
 [  3012     43      3     14  85000  22000      5     11]]
[1200000 1380000 1560000 1284000]


In [65]:
# Q20. Create Employee Score

ac = (a[:,4] + a[:,5]) * 12

sco=(ac*a[:,6])/(a[:,7]+1)


be=np.argmax(sco)# Best Employee
print(a[be])

we=np.argmin(sco)# Worst Emplyee
print(a[we])

ss=np.argsort(sco)
top5=ss[-1:-6:-1]
print(a[top5])
print(sco[top5])

[ 3004    41     1    12 80000 20000     5    10]
[ 3006    27     3     3 40000  7000     2     4]
[[ 3004    41     1    12 80000 20000     5    10]
 [ 3012    43     3    14 85000 22000     5    11]
 [ 3007    45     1    15 90000 25000     5    12]
 [ 3010    26     1     3 35000  6000     5     4]
 [ 3002    35     2     8 60000 12000     5     8]]
[545454.54545455 535000.         530769.23076923 492000.
 480000.        ]
