In [1]:
import numpy as np

# Columns:
# 0 Order_ID
# 1 Customer_Age
# 2 Category
# 3 Quantity
# 4 Unit_Price
# 5 Discount(%)
# 6 Delivery_Days
# 7 Rating
# 8 Returned (1=Yes,0=No)

data = np.array([
[1001,24,1,2,35000,10,2,5,0],
[1002,32,2,1,55000,5,5,4,0],
[1003,45,3,3,1200,15,4,3,1],
[1004,29,4,1,4500,0,1,5,0],
[1005,38,5,2,2200,20,7,2,1],
[1006,27,1,1,40000,8,3,5,0],
[1007,50,2,2,60000,12,6,4,0],
[1008,21,3,5,800,5,2,4,0],
[1009,34,4,2,7000,18,5,3,1],
[1010,41,5,4,1500,10,3,4,0],
[1011,30,1,1,50000,25,4,5,0],
[1012,36,2,3,65000,15,6,2,1],
[1013,26,3,2,1000,0,2,5,0],
[1014,48,4,1,9000,10,7,3,1],
[1015,39,5,3,1800,5,1,4,0],
[1016,23,1,2,42000,20,3,5,0],
[1017,31,2,1,58000,10,5,4,0],
[1018,44,3,4,1500,12,6,3,1],
[1019,28,4,2,8000,5,2,5,0],
[1020,35,5,5,2000,15,4,2,1],
[1021,42,1,1,47000,10,5,4,0],
[1022,37,2,2,62000,18,6,3,1],
[1023,25,3,3,900,8,2,5,0],
[1024,33,4,1,6500,0,3,4,0],
[1025,46,5,4,2100,25,7,2,1],
[1026,27,1,2,39000,12,2,5,0],
[1027,52,2,1,70000,5,6,5,0],
[1028,22,3,5,1100,10,4,4,0],
[1029,40,4,2,8500,15,5,3,1],
[1030,29,5,3,2500,5,1,5,0]
])

In [2]:
# Q1. Display the first 5 rows.

print(data[0:5,:])


[[ 1001    24     1     2 35000    10     2     5     0]
 [ 1002    32     2     1 55000     5     5     4     0]
 [ 1003    45     3     3  1200    15     4     3     1]
 [ 1004    29     4     1  4500     0     1     5     0]
 [ 1005    38     5     2  2200    20     7     2     1]]


In [3]:
# Q2. Display the last 5 rows.

print(data[-5:])

[[ 1026    27     1     2 39000    12     2     5     0]
 [ 1027    52     2     1 70000     5     6     5     0]
 [ 1028    22     3     5  1100    10     4     4     0]
 [ 1029    40     4     2  8500    15     5     3     1]
 [ 1030    29     5     3  2500     5     1     5     0]]


In [4]:
# Q3. Display all unit prices.

print(data[:,4])

[35000 55000  1200  4500  2200 40000 60000   800  7000  1500 50000 65000
  1000  9000  1800 42000 58000  1500  8000  2000 47000 62000   900  6500
  2100 39000 70000  1100  8500  2500]


In [5]:
# Q4. Display customer ages greater than 40.

print(data[data[:,1]>40,1])


[45 50 41 48 44 42 46 52]


In [6]:
# Q5. Count total orders.

print(len(data))


30


In [7]:
# Q6. Find minimum unit price.

print(np.min(data[:,4]))

800


In [8]:
# Q7. Find maximum unit price.

print(np.max(data[:,4]))

70000


In [9]:
# Q8. Find average customer age.

print(np.mean(data[:,1]))

34.46666666666667


In [10]:
# Q9. Find average rating.

print(np.mean(data[:,7]))

3.9


In [11]:
# Q10. Count returned orders.

print(np.sum(data[:,-1]==1))

10


In [12]:
# Q11. Display orders where quantity is greater than 2.

print(data[data[:,3]>2])

[[ 1003    45     3     3  1200    15     4     3     1]
 [ 1008    21     3     5   800     5     2     4     0]
 [ 1010    41     5     4  1500    10     3     4     0]
 [ 1012    36     2     3 65000    15     6     2     1]
 [ 1015    39     5     3  1800     5     1     4     0]
 [ 1018    44     3     4  1500    12     6     3     1]
 [ 1020    35     5     5  2000    15     4     2     1]
 [ 1023    25     3     3   900     8     2     5     0]
 [ 1025    46     5     4  2100    25     7     2     1]
 [ 1028    22     3     5  1100    10     4     4     0]
 [ 1030    29     5     3  2500     5     1     5     0]]


In [13]:
# Q12. Display orders where rating is 5.

print(data[data[:,7]==5])

[[ 1001    24     1     2 35000    10     2     5     0]
 [ 1004    29     4     1  4500     0     1     5     0]
 [ 1006    27     1     1 40000     8     3     5     0]
 [ 1011    30     1     1 50000    25     4     5     0]
 [ 1013    26     3     2  1000     0     2     5     0]
 [ 1016    23     1     2 42000    20     3     5     0]
 [ 1019    28     4     2  8000     5     2     5     0]
 [ 1023    25     3     3   900     8     2     5     0]
 [ 1026    27     1     2 39000    12     2     5     0]
 [ 1027    52     2     1 70000     5     6     5     0]
 [ 1030    29     5     3  2500     5     1     5     0]]


In [14]:
# Q13. Display orders with discount greater than 15%. 

print(data[data[:,5]>15])

[[ 1005    38     5     2  2200    20     7     2     1]
 [ 1009    34     4     2  7000    18     5     3     1]
 [ 1011    30     1     1 50000    25     4     5     0]
 [ 1016    23     1     2 42000    20     3     5     0]
 [ 1022    37     2     2 62000    18     6     3     1]
 [ 1025    46     5     4  2100    25     7     2     1]]


In [15]:
# Q14. Display orders delivered within 2 days.

print(data[data[:,6]<=2])

[[ 1001    24     1     2 35000    10     2     5     0]
 [ 1004    29     4     1  4500     0     1     5     0]
 [ 1008    21     3     5   800     5     2     4     0]
 [ 1013    26     3     2  1000     0     2     5     0]
 [ 1015    39     5     3  1800     5     1     4     0]
 [ 1019    28     4     2  8000     5     2     5     0]
 [ 1023    25     3     3   900     8     2     5     0]
 [ 1026    27     1     2 39000    12     2     5     0]
 [ 1030    29     5     3  2500     5     1     5     0]]


In [16]:
# Q15. Display orders costing more than ₹50,000 (Unit Price).

print(data[data[:,4]>50000])


[[ 1002    32     2     1 55000     5     5     4     0]
 [ 1007    50     2     2 60000    12     6     4     0]
 [ 1012    36     2     3 65000    15     6     2     1]
 [ 1017    31     2     1 58000    10     5     4     0]
 [ 1022    37     2     2 62000    18     6     3     1]
 [ 1027    52     2     1 70000     5     6     5     0]]


In [17]:
# Q16. Display orders that were not returned.

print(data[data[:,8]==0])

[[ 1001    24     1     2 35000    10     2     5     0]
 [ 1002    32     2     1 55000     5     5     4     0]
 [ 1004    29     4     1  4500     0     1     5     0]
 [ 1006    27     1     1 40000     8     3     5     0]
 [ 1007    50     2     2 60000    12     6     4     0]
 [ 1008    21     3     5   800     5     2     4     0]
 [ 1010    41     5     4  1500    10     3     4     0]
 [ 1011    30     1     1 50000    25     4     5     0]
 [ 1013    26     3     2  1000     0     2     5     0]
 [ 1015    39     5     3  1800     5     1     4     0]
 [ 1016    23     1     2 42000    20     3     5     0]
 [ 1017    31     2     1 58000    10     5     4     0]
 [ 1019    28     4     2  8000     5     2     5     0]
 [ 1021    42     1     1 47000    10     5     4     0]
 [ 1023    25     3     3   900     8     2     5     0]
 [ 1024    33     4     1  6500     0     3     4     0]
 [ 1026    27     1     2 39000    12     2     5     0]
 [ 1027    52     2     1 70000

In [18]:
# Q17. Display customers younger than 30.

print(data[data[:,1]<30])

[[ 1001    24     1     2 35000    10     2     5     0]
 [ 1004    29     4     1  4500     0     1     5     0]
 [ 1006    27     1     1 40000     8     3     5     0]
 [ 1008    21     3     5   800     5     2     4     0]
 [ 1013    26     3     2  1000     0     2     5     0]
 [ 1016    23     1     2 42000    20     3     5     0]
 [ 1019    28     4     2  8000     5     2     5     0]
 [ 1023    25     3     3   900     8     2     5     0]
 [ 1026    27     1     2 39000    12     2     5     0]
 [ 1028    22     3     5  1100    10     4     4     0]
 [ 1030    29     5     3  2500     5     1     5     0]]


In [19]:
# Q18. Display orders where quantity is exactly 1.

print(data[data[:,3]==1])


[[ 1002    32     2     1 55000     5     5     4     0]
 [ 1004    29     4     1  4500     0     1     5     0]
 [ 1006    27     1     1 40000     8     3     5     0]
 [ 1011    30     1     1 50000    25     4     5     0]
 [ 1014    48     4     1  9000    10     7     3     1]
 [ 1017    31     2     1 58000    10     5     4     0]
 [ 1021    42     1     1 47000    10     5     4     0]
 [ 1024    33     4     1  6500     0     3     4     0]
 [ 1027    52     2     1 70000     5     6     5     0]]


In [20]:
# Q19. Display orders where rating is less than 3.

print(data[data[:,7]<3])

[[ 1005    38     5     2  2200    20     7     2     1]
 [ 1012    36     2     3 65000    15     6     2     1]
 [ 1020    35     5     5  2000    15     4     2     1]
 [ 1025    46     5     4  2100    25     7     2     1]]


In [21]:
# Q20. Display orders taking more than 5 days for delivery.

print(data[data[:,6]>5])


[[ 1005    38     5     2  2200    20     7     2     1]
 [ 1007    50     2     2 60000    12     6     4     0]
 [ 1012    36     2     3 65000    15     6     2     1]
 [ 1014    48     4     1  9000    10     7     3     1]
 [ 1018    44     3     4  1500    12     6     3     1]
 [ 1022    37     2     2 62000    18     6     3     1]
 [ 1025    46     5     4  2100    25     7     2     1]
 [ 1027    52     2     1 70000     5     6     5     0]]


In [22]:
# Q21. Create a Revenue column.

# Revenue = Quantity * Unit_Price

revenue = data[:,3] * data[:,4]


data = np.column_stack((data, revenue))
print(data)

[[  1001     24      1      2  35000     10      2      5      0  70000]
 [  1002     32      2      1  55000      5      5      4      0  55000]
 [  1003     45      3      3   1200     15      4      3      1   3600]
 [  1004     29      4      1   4500      0      1      5      0   4500]
 [  1005     38      5      2   2200     20      7      2      1   4400]
 [  1006     27      1      1  40000      8      3      5      0  40000]
 [  1007     50      2      2  60000     12      6      4      0 120000]
 [  1008     21      3      5    800      5      2      4      0   4000]
 [  1009     34      4      2   7000     18      5      3      1  14000]
 [  1010     41      5      4   1500     10      3      4      0   6000]
 [  1011     30      1      1  50000     25      4      5      0  50000]
 [  1012     36      2      3  65000     15      6      2      1 195000]
 [  1013     26      3      2   1000      0      2      5      0   2000]
 [  1014     48      4      1   9000     10      7 

In [23]:
# Q22. Find the total Revenue.

print(np.sum(revenue))

1123500


In [24]:
# Q23. Find the order with the highest Revenue.

print(data[np.argmax(revenue)])

[  1012     36      2      3  65000     15      6      2      1 195000]


In [25]:
# Q24. Find the order with the lowest Revenue.

print(data[np.argmin(revenue)])

[1013   26    3    2 1000    0    2    5    0 2000]


In [27]:
# Q25. Find the average Revenue.

print(np.mean(revenue))


37450.0


In [29]:
# Q26. Display orders whose Revenue is greater than the average Revenue.

print(data[revenue>np.mean(revenue)])

[[  1001     24      1      2  35000     10      2      5      0  70000]
 [  1002     32      2      1  55000      5      5      4      0  55000]
 [  1006     27      1      1  40000      8      3      5      0  40000]
 [  1007     50      2      2  60000     12      6      4      0 120000]
 [  1011     30      1      1  50000     25      4      5      0  50000]
 [  1012     36      2      3  65000     15      6      2      1 195000]
 [  1016     23      1      2  42000     20      3      5      0  84000]
 [  1017     31      2      1  58000     10      5      4      0  58000]
 [  1021     42      1      1  47000     10      5      4      0  47000]
 [  1022     37      2      2  62000     18      6      3      1 124000]
 [  1026     27      1      2  39000     12      2      5      0  78000]
 [  1027     52      2      1  70000      5      6      5      0  70000]]


In [31]:
# Q27. Display the Top 5 Revenue orders.

top5 = np.argsort(revenue)[-5:]
print(data[top5])

[[  1026     27      1      2  39000     12      2      5      0  78000]
 [  1016     23      1      2  42000     20      3      5      0  84000]
 [  1007     50      2      2  60000     12      6      4      0 120000]
 [  1022     37      2      2  62000     18      6      3      1 124000]
 [  1012     36      2      3  65000     15      6      2      1 195000]]


In [32]:
# Q28. Display the Bottom 5 Revenue orders.

bottom5 = np.argsort(revenue)[:5]
print(data[bottom5])


[[1013   26    3    2 1000    0    2    5    0 2000]
 [1023   25    3    3  900    8    2    5    0 2700]
 [1003   45    3    3 1200   15    4    3    1 3600]
 [1008   21    3    5  800    5    2    4    0 4000]
 [1005   38    5    2 2200   20    7    2    1 4400]]


In [33]:
# Q29. Find the total Revenue from returned orders.

print(np.sum(revenue[data[:,8] == 1]))

391400


In [34]:
# Q30. Find the total Revenue from non-returned orders.

print(np.sum(revenue[data[:,8] == 0]))

732100


In [35]:
# Q31. Add a Final Price column.

discount_amount = revenue * data[:,5] / 100
final_price = revenue - discount_amount

data = np.column_stack((data, final_price))

print(data)

[[1.0010e+03 2.4000e+01 1.0000e+00 2.0000e+00 3.5000e+04 1.0000e+01
  2.0000e+00 5.0000e+00 0.0000e+00 7.0000e+04 6.3000e+04]
 [1.0020e+03 3.2000e+01 2.0000e+00 1.0000e+00 5.5000e+04 5.0000e+00
  5.0000e+00 4.0000e+00 0.0000e+00 5.5000e+04 5.2250e+04]
 [1.0030e+03 4.5000e+01 3.0000e+00 3.0000e+00 1.2000e+03 1.5000e+01
  4.0000e+00 3.0000e+00 1.0000e+00 3.6000e+03 3.0600e+03]
 [1.0040e+03 2.9000e+01 4.0000e+00 1.0000e+00 4.5000e+03 0.0000e+00
  1.0000e+00 5.0000e+00 0.0000e+00 4.5000e+03 4.5000e+03]
 [1.0050e+03 3.8000e+01 5.0000e+00 2.0000e+00 2.2000e+03 2.0000e+01
  7.0000e+00 2.0000e+00 1.0000e+00 4.4000e+03 3.5200e+03]
 [1.0060e+03 2.7000e+01 1.0000e+00 1.0000e+00 4.0000e+04 8.0000e+00
  3.0000e+00 5.0000e+00 0.0000e+00 4.0000e+04 3.6800e+04]
 [1.0070e+03 5.0000e+01 2.0000e+00 2.0000e+00 6.0000e+04 1.2000e+01
  6.0000e+00 4.0000e+00 0.0000e+00 1.2000e+05 1.0560e+05]
 [1.0080e+03 2.1000e+01 3.0000e+00 5.0000e+00 8.0000e+02 5.0000e+00
  2.0000e+00 4.0000e+00 0.0000e+00 4.0000e+03 3.80

In [36]:
# Q32. Find the total Final Revenue.

print(np.sum(final_price))

977199.0


In [39]:
# Q33. Find the order with the maximum Discount Amount.

discount_amount = revenue * data[:,5] / 100

idx = np.argmax(discount_amount)
print(data[idx])

[1.0120e+03 3.6000e+01 2.0000e+00 3.0000e+00 6.5000e+04 1.5000e+01
 6.0000e+00 2.0000e+00 1.0000e+00 1.9500e+05 1.6575e+05]


In [40]:
# Q34. Find the average Discount percentage.

print(np.mean(data[:,5]))

10.933333333333334


In [41]:
# Q35. Find the total Discount given.

print(np.sum(discount_amount))

146301.0


In [42]:
# Q36. Display customers receiving more than 15% Discount.

print(data[data[:,5] > 15])

[[1.0050e+03 3.8000e+01 5.0000e+00 2.0000e+00 2.2000e+03 2.0000e+01
  7.0000e+00 2.0000e+00 1.0000e+00 4.4000e+03 3.5200e+03]
 [1.0090e+03 3.4000e+01 4.0000e+00 2.0000e+00 7.0000e+03 1.8000e+01
  5.0000e+00 3.0000e+00 1.0000e+00 1.4000e+04 1.1480e+04]
 [1.0110e+03 3.0000e+01 1.0000e+00 1.0000e+00 5.0000e+04 2.5000e+01
  4.0000e+00 5.0000e+00 0.0000e+00 5.0000e+04 3.7500e+04]
 [1.0160e+03 2.3000e+01 1.0000e+00 2.0000e+00 4.2000e+04 2.0000e+01
  3.0000e+00 5.0000e+00 0.0000e+00 8.4000e+04 6.7200e+04]
 [1.0220e+03 3.7000e+01 2.0000e+00 2.0000e+00 6.2000e+04 1.8000e+01
  6.0000e+00 3.0000e+00 1.0000e+00 1.2400e+05 1.0168e+05]
 [1.0250e+03 4.6000e+01 5.0000e+00 4.0000e+00 2.1000e+03 2.5000e+01
  7.0000e+00 2.0000e+00 1.0000e+00 8.4000e+03 6.3000e+03]]


In [43]:
# Q37. Find the highest Final Payment.

idx = np.argmax(final_price)
print(data[idx])

[1.0120e+03 3.6000e+01 2.0000e+00 3.0000e+00 6.5000e+04 1.5000e+01
 6.0000e+00 2.0000e+00 1.0000e+00 1.9500e+05 1.6575e+05]


In [ ]:
# Q38. Find the lowest Final Payment.

idx = np.argmin(final_price)
print(data[idx])


[1013.   26.    3.    2. 1000.    0.    2.    5.    0. 2000. 2000.]


In [45]:

# Q39. Find the total loss due to Discounts.

print(np.sum(discount_amount))

146301.0


In [46]:
# Q40. Find the average Final Payment. 

print(np.mean(final_price))

32573.3


In [47]:
# Q41. Display all unique categories.

print(np.unique(data[:,2]))

[1. 2. 3. 4. 5.]


In [48]:
# Q42. Count the number of Laptop orders (Category = 1).

print(np.sum(data[:,2] == 1))

6


In [49]:
# Q43. Count the number of Mobile orders (Category = 2).

print(np.sum(data[:,2] == 2))

6


In [51]:
# Q44. Which category generated the highest Revenue?
 
# Revenue = Quantity * Unit_Price

for c in np.unique(data[:,2]):
    print(np.sum(revenue[data[:,2] == c]))
    

369000
622000
23800
67000
41700


In [ ]:
# Q45. Find the average Rating of each category.

for c in np.unique(data[:,2]):
    print(np.mean(data[data[:,2] == c, 7]))

4.833333333333333
3.6666666666666665
4.0
3.8333333333333335
3.1666666666666665


In [53]:
# Q46. Find the average Delivery Days of each category.

for c in np.unique(data[:,2]):
    print(np.mean(data[data[:,2] == c, 6]))

3.1666666666666665
5.666666666666667
3.3333333333333335
3.8333333333333335
3.8333333333333335


In [56]:
# Q47. Which category has the lowest average Unit Price?

for c in np.unique(data[:,2]):
    print(np.mean(data[data[:,2] == c, 4]))
    


42166.666666666664
61666.666666666664
1083.3333333333333
7250.0
2016.6666666666667


In [ ]:
# Q48. Find the average Delivery Days.

print(np.mean(data[:,6]))

3.966666666666667


In [58]:
# Q49. Find the fastest Delivery.

print(np.min(data[:,6]))

1.0


In [59]:
# Q50. Find the slowest Delivery.

print(np.max(data[:,6]))

7.0


In [60]:
# Q51. Display orders delivered in exactly 3 days.

print(data[data[:,6] == 3])

[[1.006e+03 2.700e+01 1.000e+00 1.000e+00 4.000e+04 8.000e+00 3.000e+00
  5.000e+00 0.000e+00 4.000e+04 3.680e+04]
 [1.010e+03 4.100e+01 5.000e+00 4.000e+00 1.500e+03 1.000e+01 3.000e+00
  4.000e+00 0.000e+00 6.000e+03 5.400e+03]
 [1.016e+03 2.300e+01 1.000e+00 2.000e+00 4.200e+04 2.000e+01 3.000e+00
  5.000e+00 0.000e+00 8.400e+04 6.720e+04]
 [1.024e+03 3.300e+01 4.000e+00 1.000e+00 6.500e+03 0.000e+00 3.000e+00
  4.000e+00 0.000e+00 6.500e+03 6.500e+03]]


In [61]:
# Q52. Display orders taking more than the average Delivery Days.

print(data[data[:,6] > np.mean(data[:,6])])

[[1.0020e+03 3.2000e+01 2.0000e+00 1.0000e+00 5.5000e+04 5.0000e+00
  5.0000e+00 4.0000e+00 0.0000e+00 5.5000e+04 5.2250e+04]
 [1.0030e+03 4.5000e+01 3.0000e+00 3.0000e+00 1.2000e+03 1.5000e+01
  4.0000e+00 3.0000e+00 1.0000e+00 3.6000e+03 3.0600e+03]
 [1.0050e+03 3.8000e+01 5.0000e+00 2.0000e+00 2.2000e+03 2.0000e+01
  7.0000e+00 2.0000e+00 1.0000e+00 4.4000e+03 3.5200e+03]
 [1.0070e+03 5.0000e+01 2.0000e+00 2.0000e+00 6.0000e+04 1.2000e+01
  6.0000e+00 4.0000e+00 0.0000e+00 1.2000e+05 1.0560e+05]
 [1.0090e+03 3.4000e+01 4.0000e+00 2.0000e+00 7.0000e+03 1.8000e+01
  5.0000e+00 3.0000e+00 1.0000e+00 1.4000e+04 1.1480e+04]
 [1.0110e+03 3.0000e+01 1.0000e+00 1.0000e+00 5.0000e+04 2.5000e+01
  4.0000e+00 5.0000e+00 0.0000e+00 5.0000e+04 3.7500e+04]
 [1.0120e+03 3.6000e+01 2.0000e+00 3.0000e+00 6.5000e+04 1.5000e+01
  6.0000e+00 2.0000e+00 1.0000e+00 1.9500e+05 1.6575e+05]
 [1.0140e+03 4.8000e+01 4.0000e+00 1.0000e+00 9.0000e+03 1.0000e+01
  7.0000e+00 3.0000e+00 1.0000e+00 9.0000e+03 8.10

In [62]:
# Q53. Find the percentage of orders delivered within 3 days.

print((np.sum(data[:,6] <= 3) / len(data)) * 100)

43.333333333333336


In [65]:
# Q54. Find the order with the longest delivery time that has a Rating of 5.

print(
    data[(data[:,7] == 5) &
         (data[:,6] == np.max(data[data[:,7] == 5][:,6]))]
)


[[1.027e+03 5.200e+01 2.000e+00 1.000e+00 7.000e+04 5.000e+00 6.000e+00
  5.000e+00 0.000e+00 7.000e+04 6.650e+04]]


In [66]:
# Q55. Display orders where Rating is 5 and the order was not returned.

print(data[(data[:,7] == 5) & (data[:,8] == 0)])

[[1.001e+03 2.400e+01 1.000e+00 2.000e+00 3.500e+04 1.000e+01 2.000e+00
  5.000e+00 0.000e+00 7.000e+04 6.300e+04]
 [1.004e+03 2.900e+01 4.000e+00 1.000e+00 4.500e+03 0.000e+00 1.000e+00
  5.000e+00 0.000e+00 4.500e+03 4.500e+03]
 [1.006e+03 2.700e+01 1.000e+00 1.000e+00 4.000e+04 8.000e+00 3.000e+00
  5.000e+00 0.000e+00 4.000e+04 3.680e+04]
 [1.011e+03 3.000e+01 1.000e+00 1.000e+00 5.000e+04 2.500e+01 4.000e+00
  5.000e+00 0.000e+00 5.000e+04 3.750e+04]
 [1.013e+03 2.600e+01 3.000e+00 2.000e+00 1.000e+03 0.000e+00 2.000e+00
  5.000e+00 0.000e+00 2.000e+03 2.000e+03]
 [1.016e+03 2.300e+01 1.000e+00 2.000e+00 4.200e+04 2.000e+01 3.000e+00
  5.000e+00 0.000e+00 8.400e+04 6.720e+04]
 [1.019e+03 2.800e+01 4.000e+00 2.000e+00 8.000e+03 5.000e+00 2.000e+00
  5.000e+00 0.000e+00 1.600e+04 1.520e+04]
 [1.023e+03 2.500e+01 3.000e+00 3.000e+00 9.000e+02 8.000e+00 2.000e+00
  5.000e+00 0.000e+00 2.700e+03 2.484e+03]
 [1.026e+03 2.700e+01 1.000e+00 2.000e+00 3.900e+04 1.200e+01 2.000e+00
  5.000e

In [ ]:
# Q56  Display orders where Discount > 10% and Rating ≥ 4.

data[(data[:,5] > 10) & (data[:,7] >= 4)]

array([[1.007e+03, 5.000e+01, 2.000e+00, 2.000e+00, 6.000e+04, 1.200e+01,
        6.000e+00, 4.000e+00, 0.000e+00, 1.200e+05, 1.056e+05],
       [1.011e+03, 3.000e+01, 1.000e+00, 1.000e+00, 5.000e+04, 2.500e+01,
        4.000e+00, 5.000e+00, 0.000e+00, 5.000e+04, 3.750e+04],
       [1.016e+03, 2.300e+01, 1.000e+00, 2.000e+00, 4.200e+04, 2.000e+01,
        3.000e+00, 5.000e+00, 0.000e+00, 8.400e+04, 6.720e+04],
       [1.026e+03, 2.700e+01, 1.000e+00, 2.000e+00, 3.900e+04, 1.200e+01,
        2.000e+00, 5.000e+00, 0.000e+00, 7.800e+04, 6.864e+04]])

In [68]:
# Q57. Display customers older than 35 who bought Mobiles.

print(data[(data[:,1] > 35) & (data[:,2] == 2)])

[[1.0070e+03 5.0000e+01 2.0000e+00 2.0000e+00 6.0000e+04 1.2000e+01
  6.0000e+00 4.0000e+00 0.0000e+00 1.2000e+05 1.0560e+05]
 [1.0120e+03 3.6000e+01 2.0000e+00 3.0000e+00 6.5000e+04 1.5000e+01
  6.0000e+00 2.0000e+00 1.0000e+00 1.9500e+05 1.6575e+05]
 [1.0220e+03 3.7000e+01 2.0000e+00 2.0000e+00 6.2000e+04 1.8000e+01
  6.0000e+00 3.0000e+00 1.0000e+00 1.2400e+05 1.0168e+05]
 [1.0270e+03 5.2000e+01 2.0000e+00 1.0000e+00 7.0000e+04 5.0000e+00
  6.0000e+00 5.0000e+00 0.0000e+00 7.0000e+04 6.6500e+04]]


In [69]:
# Q58. Display orders where Quantity > 3 and Rating < 4.

print(data[(data[:,3] > 3) & (data[:,7] < 4)])

[[1.018e+03 4.400e+01 3.000e+00 4.000e+00 1.500e+03 1.200e+01 6.000e+00
  3.000e+00 1.000e+00 6.000e+03 5.280e+03]
 [1.020e+03 3.500e+01 5.000e+00 5.000e+00 2.000e+03 1.500e+01 4.000e+00
  2.000e+00 1.000e+00 1.000e+04 8.500e+03]
 [1.025e+03 4.600e+01 5.000e+00 4.000e+00 2.100e+03 2.500e+01 7.000e+00
  2.000e+00 1.000e+00 8.400e+03 6.300e+03]]


In [74]:
# Q59. Create a Premium Order column.Revenue > ₹80,000

print(np.where(revenue > 80000, "Yes", "No"))

['No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No'
 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No']


In [75]:
# Q60. Create an Expensive Product column.Unit Price > ₹40,000

expensive = np.where(data[:,4] > 40000, "Yes", "No")
print(expensive)


['No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No'
 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes'
 'No' 'No' 'No']


In [76]:
# Q61. Create a Senior Customer column.Age > 40

senior = np.where(data[:,1] > 40, "Senior", "Regular")
print(senior)

['Regular' 'Regular' 'Senior' 'Regular' 'Regular' 'Regular' 'Senior'
 'Regular' 'Regular' 'Senior' 'Regular' 'Regular' 'Regular' 'Senior'
 'Regular' 'Regular' 'Regular' 'Senior' 'Regular' 'Regular' 'Senior'
 'Regular' 'Regular' 'Regular' 'Senior' 'Regular' 'Senior' 'Regular'
 'Regular' 'Regular']


In [78]:
# Q62. Display the Top 10 Revenue orders.

top10 = np.argsort(revenue)[-10:][::-1]
print(data[top10,0])

[1012. 1022. 1007. 1016. 1026. 1027. 1001. 1017. 1002. 1011.]


In [81]:
# Q63. Display the Top 5 highest-rated orders.

top5 = np.argsort(data[:,7])[-5:][::-1]
print(data[top5,0])

[1030. 1027. 1026. 1023. 1019.]


In [83]:
# Q64. Display the Top 5 highest discounts.

top = np.argsort(data[:,5])[-5:][::-1]
print(top)

[24 10 15  4  8]


In [85]:
# Q65. Find the customer who spent the most after discount.

print(data[np.argmax(final_price)])

[1.0120e+03 3.6000e+01 2.0000e+00 3.0000e+00 6.5000e+04 1.5000e+01
 6.0000e+00 2.0000e+00 1.0000e+00 1.9500e+05 1.6575e+05]


In [86]:
#Q66. Find the percentage of returned orders.

print((np.sum(data[:,8] == 1) / len(data)) * 100)

33.33333333333333


In [87]:
# Q67. Find the lowest-rated Mobile order.(Category = 2)

mobiles = data[data[:,2] == 2]

mobiles[np.argmin(mobiles[:,7])]

array([1.0120e+03, 3.6000e+01, 2.0000e+00, 3.0000e+00, 6.5000e+04,
       1.5000e+01, 6.0000e+00, 2.0000e+00, 1.0000e+00, 1.9500e+05,
       1.6575e+05])

In [90]:
# Q68. Find the order closest to the average Revenue.

avg = np.mean(revenue)

idx = np.argmin(np.abs(revenue - avg))

print(data[idx])

[1.006e+03 2.700e+01 1.000e+00 1.000e+00 4.000e+04 8.000e+00 3.000e+00
 5.000e+00 0.000e+00 4.000e+04 3.680e+04]


In [91]:
# Q69. Find the Revenue standard deviation.

print(np.std(revenue))


45704.21388304001


In [92]:
# Q70. Find the Revenue variance.

print(np.var(revenue))

2088875166.6666667


In [93]:
# Q71. Find the correlation between Quantity and Revenue.

print(np.corrcoef(data[:,3], revenue))

[[ 1.         -0.25029544]
 [-0.25029544  1.        ]]


In [94]:
# Q72. Create a Customer Score.

# Score = (Rating * 20) + (Quantity * 5) - Delivery_Days

score = (data[:,7] * 20) + (data[:,3] * 5) - data[:,6]
print(score)

[108.  80.  71. 104.  43. 102.  84. 103.  65.  97. 101.  49. 108.  58.
  94. 107.  80.  74. 108.  61.  80.  64. 113.  82.  53. 108.  99. 101.
  65. 114.]


In [ ]:
# Q73. Display the Top 5 customers by Score.
top5 = np.argsort(score)[-5:][::-1]

print("Order ID   Score")
for i in top5:
    print(data[i, 0], score[i])


Order ID   Score
1030.0 114.0
1023.0 113.0
1019.0 108.0
1026.0 108.0
1001.0 108.0


In [101]:

# Q74. Display the Bottom 5 customers by Score.

b5 = np.argsort(score)[:5]

print("Order ID   Score")
for i in b5:
    print(data[i, 0], score[i])


Order ID   Score
1005.0 43.0
1012.0 49.0
1025.0 53.0
1014.0 58.0
1020.0 61.0


In [105]:
# Q75 Find the Best Order.
 
# Best Score =(Rating * Final_Price) / Delivery_Days

best = (data[:,7] * final_price) / data[:,6]

idx = np.argmax(best)
print(data[idx,0])
print(best[idx])


1026.0
171600.0
