In [1]:
import numpy as np

# Columns:
# [Order_ID, Customer_Age, Product_Category,
#  Quantity, Unit_Price, Discount(%),
#  Rating, Delivery_Days]

a = np.array([
    [1001, 22, 1, 2, 500, 10, 4, 2],
    [1002, 35, 2, 1, 1200, 5, 5, 4],
    [1003, 28, 3, 4, 300, 0, 3, 3],
    [1004, 45, 1, 3, 700, 15, 5, 5],
    [1005, 31, 4, 2, 1500, 20, 4, 7],
    [1006, 26, 2, 5, 800, 10, 2, 6],
    [1007, 39, 3, 1, 400, 0, 5, 2],
    [1008, 29, 4, 6, 250, 5, 3, 3],
    [1009, 50, 1, 2, 900, 25, 4, 8],
    [1010, 23, 2, 4, 1100, 10, 5, 4],
    [1011, 37, 3, 3, 600, 15, 2, 5],
    [1012, 42, 4, 1, 2000, 30, 5, 10]
])




In [2]:
print(np.sum(a[:,3]*a[:,4])) # Find total revenue before discount.

24400


In [3]:
print(np.mean(a[:,1])) # Average Customer Age

33.916666666666664


In [4]:
print(np.max(a[:,4])) # Maximum Unit Price

2000


In [5]:
print(np.sum(a[:,-2]==5)) # Count Orders With Rating 5

5


In [6]:
print(a[a[:,-1]>5]) # Orders Delivered In More Than 5 Days

[[1005   31    4    2 1500   20    4    7]
 [1006   26    2    5  800   10    2    6]
 [1009   50    1    2  900   25    4    8]
 [1012   42    4    1 2000   30    5   10]]


In [7]:
b=(np.column_stack((a,a[:,3]*a[:,4]*(1-5/100)))) # Final Revenue Column
print(b.shape)

print(np.column_stack((a[:,3]*a[:,4]*(1-5/100))))


(12, 9)
[[ 950. 1140. 1140. 1995. 2850. 3800.  380. 1425. 1710. 4180. 1710. 1900.]]


In [8]:
r=a[:,3]*a[:,4] # Order With Highest Final Revenue
td = r * (a[:,5] / 100)
fr=r-td
print(np.max(fr))
print(a[np.argmax(fr)])



3960.0
[1010   23    2    4 1100   10    5    4]


#### imp
""" Revenue before discount
R=Q×P

Discount amount
TD=R×D/100
	​

Final Revenue
FR=R−TD

Substituting R=Q×P:

FR=(Q×P)−(Q×P×d/100)
	​



Factoring out Q×P:

FR=Q×P×(1-D/100)
	​

"""q=quantity
p=unit price
d=discount

In [9]:
r=a[:,3]*a[:,4] # Total Revenue After Discount
d=r*a[:,5]/100
fv=r-d

print(np.sum(fv))

21090.0


In [10]:
for cat in np.unique(a[:,2]): #  Average Rating Per Category
    avg_rating = np.mean(a[a[:,2] == cat][:,6])
    print(f"Category {cat} -> {avg_rating}")

Category 1 -> 4.333333333333333
Category 2 -> 4.0
Category 3 -> 3.3333333333333335
Category 4 -> 4.0


In [11]:
# Age > Average Age AND Rating < Average Rating

print(a[(a[:,1]>np.mean(a[:,1])) & (a[:,-2]<np.mean(a[:,-2]))])

[[1011   37    3    3  600   15    2    5]]


In [12]:
# Top 3 Orders By Final Revenue

r=a[:,3]*a[:,4]

d=r*(a[:,5]/100)

f=r-d


top3 = np.argsort(f)[-1:-4:-1]

print(f[top3])   # Top 3 revenues
print(a[top3])   # Corresponding rows



[3960. 3600. 2400.]
[[1010   23    2    4 1100   10    5    4]
 [1006   26    2    5  800   10    2    6]
 [1005   31    4    2 1500   20    4    7]]


In [13]:
# Q12. Category Generating Maximum Revenue  

r = a[:,3] * a[:,4]
d = r * (a[:,5] / 100)
f = r - d

max_category = None
max_revenue = 0

for cat in np.unique(a[:,2]):
    total_rev = np.sum(f[a[:,2] == cat])

    if total_rev > max_revenue:
        max_revenue = total_rev
        max_category = cat

print("Category:", max_category)
print("Revenue:", max_revenue) 

Category: 2
Revenue: 8700.0


In [14]:
# Customer Whose Revenue Is Closest To Average Revenue

r = a[:,3] * a[:,4]
d = r * (a[:,5] / 100)
f = r - d

print((a[np.argmin(np.abs(f - np.mean(f)))]))#order of closest to average
print(np.mean(f))#avereage 
print(f[np.argmin(np.abs(f - np.mean(f)))])# closest to average

[1004   45    1    3  700   15    5    5]
1757.5
1785.0


In [15]:
# Category-wise Revenue Percentage Contribution
r = a[:,3] * a[:,4]
d = r * (a[:,5] / 100)
f = r - d
tr=np.sum(f)# total revenue

for cat in np.unique(a[:,2]):
    cr = np.sum(f[a[:,2] == cat])# category revenue
    
    c=(cr/tr)*100
    print(cat,c)




1 19.132290184921764
2 41.25177809388336
3 14.841156946420103
4 24.774774774774773


In [16]:
# Score
r = a[:,3] * a[:,4]
d = r * (a[:,5] / 100)
f = r - d

score = (f * a[:,6]) / (a[:,7] + 1)

best_idx = np.argmax(score)
worst_idx = np.argmin(score)
top5_idx = np.argsort(score)[-5:][::-1]

print("Best Order:\n", a[best_idx])
print("Best Score:\n", score[best_idx])

print("\nWorst Order:\n", a[worst_idx])
print("Worst Score:\n", score[worst_idx])

print("\nTop 5 Orders:\n", a[top5_idx])
print("\nTop 5 Scores:\n", score[top5_idx])

Best Order:
 [1010   23    2    4 1100   10    5    4]
Best Score:
 3960.0

Worst Order:
 [1011   37    3    3  600   15    2    5]
Worst Score:
 510.0

Top 5 Orders:
 [[1010   23    2    4 1100   10    5    4]
 [1004   45    1    3  700   15    5    5]
 [1005   31    4    2 1500   20    4    7]
 [1001   22    1    2  500   10    4    2]
 [1002   35    2    1 1200    5    5    4]]

Top 5 Scores:
 [3960.  1487.5 1200.  1200.  1140. ]
